#include "MasteringComponent.h"
#include "dozi/core/MasteringMp3Encoder.h"
#include "dozi/core/MasteringDiagnostics.h"
#include "dozi/core/MasteringStyles.h"
#include "dozi/core/MasteringAnalyzer.h"
#include "dozi/core/MasteringRenderer.h"
#include "dozi/core/MasteringReport.h"
#include "dozi/core/MasteringTargets.h"

#include <algorithm>
#include <cmath>

namespace {
using Type=dozi::core::MasteringModuleType;

struct AnalysisJobResult {
    std::optional<dozi::core::MasteringAnalysisResult> source,reference;
    std::optional<dozi::core::MasteringPlan> plan;
    std::optional<dozi::core::MasteringHealthScore> health;
    juce::String error;
};
dozi::core::HealthScoreConfig healthConfig(const dozi::core::MasteringPlan&plan,const std::optional<dozi::core::MasteringAnalysisResult>&reference){dozi::core::HealthScoreConfig config;config.targetLufs=plan.targetIntegratedLufs;config.truePeakCeilingDbtp=plan.truePeakCeilingDbtp;if(reference&&reference->bands.size()==config.referenceBandRelativeDb.size()){config.referenceBandRelativeDb.clear();for(const auto&band:reference->bands)config.referenceBandRelativeDb.push_back(band.energyDb);}return config;}
}

void PlaybackMeter::setLevels(float lp,float rp,float lr,float rr){leftPeak_=lp;rightPeak_=rp;leftRms_=lr;rightRms_=rr;}
void PlaybackMeter::reset(){setLevels(-100,-100,-100,-100);repaint();}
void PlaybackMeter::paint(juce::Graphics&g){
    g.fillAll(juce::Colour(0xff171a20));
    const auto dbToX=[](float db,float width){return juce::jmap(juce::jlimit(-60.0f,0.0f,db),-60.0f,0.0f,0.0f,width);};
    auto row=[&](int y,const char*name,float rms,float peak){
        g.setColour(juce::Colours::white);g.drawText(name,8,y,22,18,juce::Justification::centred);
        const juce::Rectangle<float> track(34.0f,static_cast<float>(y+2),static_cast<float>(getWidth()-126),14.0f);
        g.setColour(juce::Colour(0xff29313b));g.fillRoundedRectangle(track,3);
        g.setColour(juce::Colour(0xff4db6d8));g.fillRoundedRectangle(track.withWidth(dbToX(rms,track.getWidth())),3);
        const auto px=track.getX()+dbToX(peak,track.getWidth());g.setColour(peak>=-1?juce::Colours::red:peak>=-6?juce::Colours::orange:juce::Colour(0xff8dd35f));g.fillRect(px,track.getY(),2.0f,track.getHeight());
        g.setColour(juce::Colours::white);g.drawText(juce::String(peak,1)+" dBFS",getWidth()-86,y,82,18,juce::Justification::centredRight);
    };
    row(4,"L",leftRms_,leftPeak_);row(24,"R",rightRms_,rightPeak_);
}

DoziLookAndFeel::DoziLookAndFeel(){
    setColour(juce::TextButton::buttonColourId,juce::Colour(0xff222d3a));
    setColour(juce::TextButton::buttonOnColourId,juce::Colour(0xff173c40));
    setColour(juce::TextButton::textColourOffId,juce::Colour(0xff9ba8b5));
    setColour(juce::TextButton::textColourOnId,juce::Colour(0xfff2f5f7));
    setColour(juce::ComboBox::backgroundColourId,juce::Colour(0xff182230));
    setColour(juce::ComboBox::outlineColourId,juce::Colour(0xff2b3a49));
    setColour(juce::ComboBox::textColourId,juce::Colour(0xfff2f5f7));
}
void DoziLookAndFeel::drawButtonBackground(juce::Graphics&g,juce::Button&button,const juce::Colour&,bool over,bool down){
    auto colour=button.getToggleState()?juce::Colour(0xff173c40):juce::Colour(0xff222d3a);
    if(over)colour=colour.brighter(0.10f);if(down)colour=colour.darker(0.12f);
    g.setColour(colour.withMultipliedAlpha(button.isEnabled()?1.0f:0.45f));g.fillRoundedRectangle(button.getLocalBounds().toFloat(),6.0f);
    if(button.getToggleState()){g.setColour(juce::Colour(0xff38d8be));g.fillRoundedRectangle(0.0f,static_cast<float>(button.getHeight()-2),static_cast<float>(button.getWidth()),2.0f,1.0f);}
}
void DoziLookAndFeel::drawButtonText(juce::Graphics&g,juce::TextButton&button,bool,bool){g.setFont(juce::FontOptions(12.0f).withStyle("Bold"));g.setColour(button.findColour(button.getToggleState()?juce::TextButton::textColourOnId:juce::TextButton::textColourOffId).withMultipliedAlpha(button.isEnabled()?1.0f:0.45f));g.drawFittedText(button.getButtonText(),button.getLocalBounds().reduced(7,2),juce::Justification::centred,1);}

MasteringComponent::MasteringComponent():progress(progressValue){
    setLookAndFeel(&doziLookAndFeel);formats.registerBasicFormats();setAudioChannels(0,2);startTimerHz(60);
    setWantsKeyboardFocus(true);addKeyListener(this);
    title.setText("DOZI  /  MASTERING",juce::dontSendNotification);title.setFont(juce::FontOptions(30).withStyle("Bold"));title.setJustificationType(juce::Justification::centred);
    status.setText("Drop a stereo WAV, AIFF, FLAC, or MP3 here",juce::dontSendNotification);status.setJustificationType(juce::Justification::centred);
    referenceStatus.setText("Reference: none",juce::dontSendNotification);referenceStatus.setJustificationType(juce::Justification::centred);
    workflowLabel.setText("01  LOAD MIX    >    02  ANALYZE + PLAN    >    03  AUDITION    >    04  EXPORT",juce::dontSendNotification);workflowLabel.setJustificationType(juce::Justification::centred);workflowLabel.setColour(juce::Label::textColourId,juce::Colour(0xff55e0c1));
    formatBadge.setJustificationType(juce::Justification::centred);formatBadge.setColour(juce::Label::backgroundColourId,juce::Colour(0xff633c16));formatBadge.setColour(juce::Label::textColourId,juce::Colour(0xffffcf80));formatBadge.setVisible(false);
    for(auto*editor:{&results,&beforeSummary,&afterSummary}){editor->setMultiLine(true);editor->setReadOnly(true);editor->setColour(juce::TextEditor::backgroundColourId,juce::Colour(0xff171a20));}
    for(auto*c:std::array<juce::Component*,52>{&title,&status,&referenceStatus,&workflowLabel,&formatBadge,&transportTime,&chooseButton,&referenceButton,&clearReferenceButton,&analyseButton,&previewButton,&exportButton,&playButton,&deviceButton,&cancelButton,&saveProjectButton,&openProjectButton,&recentProjectsButton,&saveVersionButton,&restoreVersionButton,&compareVersionButton,&abButton,&loudnessMatchButton,&loopTrackButton,&loopSelectionButton,&monitorMuteButton,&eq,&dynamicEq,&deEsser,&comp,&multiband,&saturation,&stereo,&limiter,&stylePreset,&targetPreset,&seek,&target,&ceiling,&width,&saturationDrive,&saturationMix,&monitorLevel,&playbackMeter,&detailsButton,&doziPrompt,&doziApplyButton,&doziUndoButton,&beforeSummary,&afterSummary,&moduleInspector,&waveformView})addAndMakeVisible(c);
    for(auto*button:{&consoleViewButton,&waveViewButton,&chainViewButton,&deliverViewButton}){addAndMakeVisible(button);button->setClickingTogglesState(true);button->setRadioGroupId(1001);}
    for(auto*control:std::array<juce::Component*,40>{static_cast<juce::Component*>(&chooseButton),&referenceButton,&clearReferenceButton,&analyseButton,&previewButton,&exportButton,&playButton,&deviceButton,&cancelButton,&saveProjectButton,&openProjectButton,&recentProjectsButton,&saveVersionButton,&restoreVersionButton,&compareVersionButton,&detailsButton,&doziApplyButton,&doziUndoButton,&abButton,&loudnessMatchButton,&loopTrackButton,&loopSelectionButton,&monitorMuteButton,&eq,&dynamicEq,&deEsser,&comp,&multiband,&saturation,&stereo,&limiter,&stylePreset,&targetPreset,&seek,&target,&ceiling,&width,&saturationDrive,&saturationMix,&monitorLevel}){control->setWantsKeyboardFocus(false);control->setMouseClickGrabsKeyboardFocus(false);}
    addAndMakeVisible(results);addAndMakeVisible(progress);results.setVisible(false);
    for(auto*b:{&eq,&comp,&stereo,&limiter})b->setToggleState(true,juce::dontSendNotification);
    for(auto*b:{&dynamicEq,&deEsser,&multiband,&saturation})b->setToggleState(false,juce::dontSendNotification);
    targetPreset.addItem("Spotify Normal",1);targetPreset.addItem("Spotify Loud",2);targetPreset.addItem("Spotify Quiet",3);targetPreset.addItem("Custom",4);targetPreset.setSelectedId(1,juce::dontSendNotification);
    int styleItem=1;for(const auto&preset:dozi::core::factoryMasteringStyles())stylePreset.addItem(preset.name,styleItem++);stylePreset.setSelectedId(2,juce::dontSendNotification);
    stylePreset.setLookAndFeel(&compactComboLookAndFeel);targetPreset.setLookAndFeel(&compactComboLookAndFeel);
    target.setRange(-24,-8,.1);target.setValue(-14);target.setTextValueSuffix(" LUFS target");
    ceiling.setRange(-3,-.1,.1);ceiling.setValue(-1);ceiling.setTextValueSuffix(" dBTP ceiling");
    width.setRange(0,1,.01);width.setValue(1);width.setTextValueSuffix(" width");
    saturationDrive.setRange(0,12,.1);saturationDrive.setValue(2);saturationDrive.setTextValueSuffix(" dB drive");
    saturationMix.setRange(0,1,.01);saturationMix.setValue(.5);saturationMix.setTextValueSuffix(" saturation mix");
    monitorLevel.setRange(-60,6,.1);monitorLevel.setValue(0);monitorLevel.setTextValueSuffix(" dB Monitor");monitorLevel.setTextBoxStyle(juce::Slider::TextBoxRight,false,105,24);monitorLevel.setDoubleClickReturnValue(true,0);
    doziPrompt.setMultiLine(false);doziPrompt.setReturnKeyStartsNewLine(false);doziPrompt.setTextToShowWhenEmpty("Talk to Dozi - e.g. 'reduce the bass a little'",juce::Colour(0xff8f9bab));doziUndoButton.setEnabled(false);
    seek.setRange(0,1,.001);seek.setTextBoxStyle(juce::Slider::NoTextBox,false,0,0);transportTime.setText("0:00 / 0:00",juce::dontSendNotification);transportTime.setFont(juce::FontOptions(12.0f));transportTime.setJustificationType(juce::Justification::centredRight);transportTime.setColour(juce::Label::textColourId,juce::Colours::white);transportTime.setInterceptsMouseClicks(false,false);transportTime.toFront(false);cancelButton.setVisible(false);clearReferenceButton.setEnabled(false);analyseButton.setEnabled(false);previewButton.setEnabled(false);exportButton.setEnabled(false);playButton.setEnabled(false);abButton.setEnabled(false);loopSelectionButton.setEnabled(false);loudnessMatchButton.setToggleState(true,juce::dontSendNotification);saveProjectButton.setEnabled(false);saveVersionButton.setEnabled(false);compareVersionButton.setEnabled(false);
    chooseButton.onClick=[this]{choose();};referenceButton.onClick=[this]{chooseReference();};clearReferenceButton.onClick=[this]{clearReference();};analyseButton.onClick=[this]{analyse();};previewButton.onClick=[this]{renderPreview();};exportButton.onClick=[this]{exportMaster();};cancelButton.onClick=[this]{cancel();};
    saveVersionButton.onClick=[this]{saveVersion();};restoreVersionButton.onClick=[this]{restoreVersion();};compareVersionButton.onClick=[this]{compareVersion();};
    saveProjectButton.onClick=[this]{saveProject();};openProjectButton.onClick=[this]{openProject();};recentProjectsButton.onClick=[this]{showRecentSessions();};
    detailsButton.setClickingTogglesState(true);detailsButton.onClick=[this]{const auto details=detailsButton.getToggleState();detailsButton.setButtonText(details?"Hide Technical Details":"Show Technical Details");results.setVisible(details);beforeSummary.setVisible(!details);afterSummary.setVisible(!details);};
    moduleInspector.onPlanChanged=[this]{if(plan){applyPlanToControls(*plan);refreshText();status.setText("Processor settings changed - click Render Preview to apply",juce::dontSendNotification);}};
    const auto bindModuleToggle=[this](juce::ToggleButton&button,Type type){auto*control=&button;button.onClick=[this,control,type]{if(!plan)return;for(auto&module:plan->modules)if(module.type==type)module.bypassed=!control->getToggleState();moduleInspector.setPlan(&*plan);refreshText();};};
    bindModuleToggle(eq,Type::linearPhaseEq);bindModuleToggle(dynamicEq,Type::dynamicEq);bindModuleToggle(deEsser,Type::deEsser);bindModuleToggle(comp,Type::broadbandCompressor);bindModuleToggle(multiband,Type::multibandCompressor);bindModuleToggle(saturation,Type::saturation);bindModuleToggle(stereo,Type::stereoWidthMonoBass);bindModuleToggle(limiter,Type::truePeakLimiter);
    targetPreset.onChange=[this]{const std::array ids{"spotify-normal","spotify-loud","spotify-quiet"};const auto selected=targetPreset.getSelectedId();if(selected>=1&&selected<=3)if(const auto preset=dozi::core::masteringTarget(ids[static_cast<std::size_t>(selected-1)])){target.setValue(preset->integratedLufs);ceiling.setValue(preset->truePeakCeilingDbtp);}};
    stylePreset.onChange=[this]{if(!plan||!before)return;const auto index=stylePreset.getSelectedItemIndex();const auto&styles=dozi::core::factoryMasteringStyles();if(index>=0&&index<static_cast<int>(styles.size())){dozi::core::applyMasteringStyle(*plan,*before,styles[static_cast<std::size_t>(index)]);applyPlanToControls(*plan);moduleInspector.setPlan(&*plan);refreshText();status.setText("Preset selected - click Render Preview to apply",juce::dontSendNotification);}};
    target.onValueChange=[this]{if(!plan||!before)return;plan->targetIntegratedLufs=target.getValue();for(auto&module:plan->modules)if(module.type==Type::truePeakLimiter)module.parameters["inputGainDb"]=std::clamp(plan->targetIntegratedLufs-before->integratedLufs,-12.0,12.0);moduleInspector.setPlan(&*plan);refreshText();};
    ceiling.onValueChange=[this]{if(!plan)return;plan->truePeakCeilingDbtp=ceiling.getValue();for(auto&module:plan->modules)if(module.type==Type::truePeakLimiter)module.parameters["ceilingDbtp"]=plan->truePeakCeilingDbtp;moduleInspector.setPlan(&*plan);refreshText();};
    playButton.onClick=[this]{togglePlayback();};
    abButton.onClick=[this]{switchAB();};loudnessMatchButton.onClick=[this]{updatePlaybackGain();};monitorLevel.onValueChange=[this]{updateMonitorGain();};monitorMuteButton.onClick=[this]{updateMonitorGain();};seek.onValueChange=[this]{seekBoth(seek.getValue()*beforeTransport.getLengthInSeconds());};
    waveformView.onSeek=[this](double seconds){seekBoth(seconds);};
    waveformView.onSelectionChanged=[this](double start,double end){updateLoopControls(start,end);};
    loopTrackButton.onClick=[this]{if(loopTrackButton.getToggleState())loopSelectionButton.setToggleState(false,juce::dontSendNotification);};
    loopSelectionButton.onClick=[this]{if(loopSelectionButton.getToggleState()&&waveformView.hasSelection()){loopTrackButton.setToggleState(false,juce::dontSendNotification);seekBoth(waveformView.selectionStartSeconds());}};
    deviceButton.onClick=[this]{showAudioDeviceSettings();};
    doziApplyButton.onClick=[this]{submitDoziRequest();};doziUndoButton.onClick=[this]{undoDoziRequest();};doziPrompt.onReturnKey=[this]{submitDoziRequest();};
    consoleViewButton.onClick=[this]{showView(View::console);};waveViewButton.onClick=[this]{showView(View::wave);};chainViewButton.onClick=[this]{showView(View::chain);};deliverViewButton.onClick=[this]{showView(View::deliver);};
    installTransportKeyListeners(*this);
    loadRecentSessions();
    setSize(1280,940);showView(View::console);
    juce::MessageManager::callAsync([safe=juce::Component::SafePointer<MasteringComponent>(this)]{if(safe)safe->restoreRecoverySession();});
}

MasteringComponent::~MasteringComponent(){stylePreset.setLookAndFeel(nullptr);targetPreset.setLookAndFeel(nullptr);setLookAndFeel(nullptr);cancel();if(worker&&worker->joinable())worker->join();saveRecoverySession();beforeTransport.setSource(nullptr);afterTransport.setSource(nullptr);if(previewIsTemporary&&previewFile.existsAsFile())previewFile.deleteFile();shutdownAudio();}
void MasteringComponent::prepareToPlay(int n,double r){playbackSampleRate=r;beforePlaybackBuffer.setSize(2,n);afterPlaybackBuffer.setSize(2,n);beforeTransport.prepareToPlay(n,r);afterTransport.prepareToPlay(n,r);}void MasteringComponent::releaseResources(){beforeTransport.releaseResources();afterTransport.releaseResources();beforePlaybackBuffer.setSize(0,0);afterPlaybackBuffer.setSize(0,0);}void MasteringComponent::getNextAudioBlock(const juce::AudioSourceChannelInfo&i){if(!i.buffer||i.numSamples<=0)return;const auto channels=juce::jmax(1,i.buffer->getNumChannels());beforePlaybackBuffer.setSize(channels,i.numSamples,false,false,true);afterPlaybackBuffer.setSize(channels,i.numSamples,false,false,true);beforePlaybackBuffer.clear();afterPlaybackBuffer.clear();juce::AudioSourceChannelInfo beforeInfo(&beforePlaybackBuffer,0,i.numSamples),afterInfo(&afterPlaybackBuffer,0,i.numSamples);beforeTransport.getNextAudioBlock(beforeInfo);afterTransport.getNextAudioBlock(afterInfo);const auto requestedBlend=targetMasteredBlend.load();const auto gain=masteredPlaybackGain.load();const auto requestedMonitorGain=monitorGain.load();const auto step=1.0f/static_cast<float>(juce::jmax(1.0,playbackSampleRate*0.01));for(int sample=0;sample<i.numSamples;++sample){if(currentMasteredBlend<requestedBlend)currentMasteredBlend=juce::jmin(requestedBlend,currentMasteredBlend+step);else if(currentMasteredBlend>requestedBlend)currentMasteredBlend=juce::jmax(requestedBlend,currentMasteredBlend-step);if(currentMonitorGain<requestedMonitorGain)currentMonitorGain=juce::jmin(requestedMonitorGain,currentMonitorGain+step);else if(currentMonitorGain>requestedMonitorGain)currentMonitorGain=juce::jmax(requestedMonitorGain,currentMonitorGain-step);for(int channel=0;channel<channels;++channel){const auto originalSample=beforePlaybackBuffer.getSample(channel,sample);const auto masteredSample=afterPlaybackBuffer.getSample(channel,sample)*gain;const auto auditionSample=originalSample*(1.0f-currentMasteredBlend)+masteredSample*currentMasteredBlend;i.buffer->setSample(channel,i.startSample+sample,auditionSample*currentMonitorGain);}}const auto db=[](float v){return juce::Decibels::gainToDecibels(v,-100.0f);};const auto measure=[&](int channel,bool rms){const auto c=juce::jmin(channel,i.buffer->getNumChannels()-1);return rms?i.buffer->getRMSLevel(c,i.startSample,i.numSamples):i.buffer->getMagnitude(c,i.startSample,i.numSamples);};playbackMeter.setLevels(db(measure(0,false)),db(measure(1,false)),db(measure(0,true)),db(measure(1,true)));}
void MasteringComponent::paint(juce::Graphics&g){g.fillAll(juce::Colour(0xff080b10));g.setColour(juce::Colour(0xff111722));g.fillRect(getLocalBounds().removeFromTop(92));g.setColour(juce::Colour(0xff182230));g.fillRect(getLocalBounds().removeFromBottom(142));g.setColour(juce::Colour(0xff38d8be));g.fillRect(0,90,getWidth(),2);g.setColour(juce::Colour(0xff2b3a49));g.fillRect(0,getHeight()-143,getWidth(),1);}
void MasteringComponent::showAudioDeviceSettings(){for(auto*type:deviceManager.getAvailableDeviceTypes())if(type!=nullptr)type->scanForDevices();auto selector=std::make_unique<juce::AudioDeviceSelectorComponent>(deviceManager,0,0,1,2,false,false,true,false);selector->setSize(520,430);juce::CallOutBox::launchAsynchronously(std::move(selector),deviceButton.getScreenBounds(),nullptr);}
void MasteringComponent::resized(){
    auto bounds=getLocalBounds();auto header=bounds.removeFromTop(92).reduced(24,12);auto brand=header.removeFromLeft(215);title.setBounds(brand);title.setJustificationType(juce::Justification::centredLeft);
    auto project=header.removeFromLeft(320).removeFromTop(30);saveProjectButton.setBounds(project.removeFromLeft(96));project.removeFromLeft(6);openProjectButton.setBounds(project.removeFromLeft(96));project.removeFromLeft(6);recentProjectsButton.setBounds(project.removeFromLeft(112));
    auto views=header.removeFromRight(360);for(auto*button:{&consoleViewButton,&waveViewButton,&chainViewButton,&deliverViewButton}){button->setBounds(views.removeFromLeft(86).reduced(2,0));}
    auto selectors=header.reduced(10,0);stylePreset.setBounds(selectors.removeFromLeft(190).withHeight(32));selectors.removeFromLeft(8);targetPreset.setBounds(selectors.removeFromLeft(140).withHeight(32));

    auto transport=bounds.removeFromBottom(142).reduced(24,10);playbackMeter.setBounds(transport.removeFromTop(46));transport.removeFromTop(5);auto scrub=transport.removeFromTop(25);transportTime.setBounds(scrub.removeFromRight(145));seek.setBounds(scrub);auto controls=transport.removeFromTop(38);playButton.setBounds(controls.removeFromLeft(90));controls.removeFromLeft(6);loopTrackButton.setBounds(controls.removeFromLeft(110));controls.removeFromLeft(6);loopSelectionButton.setBounds(controls.removeFromLeft(190));controls.removeFromLeft(12);abButton.setBounds(controls.removeFromLeft(170));controls.removeFromLeft(6);loudnessMatchButton.setBounds(controls.removeFromLeft(145));controls.removeFromLeft(12);monitorLevel.setBounds(controls.removeFromLeft(230));monitorMuteButton.setBounds(controls.removeFromLeft(80));controls.removeFromLeft(8);deviceButton.setBounds(controls.removeFromLeft(120));

    auto content=bounds.reduced(28,16);status.setBounds(content.removeFromTop(24));referenceStatus.setBounds(content.removeFromTop(22));formatBadge.setBounds(content.removeFromTop(24).reduced(300,1));progress.setBounds(content.removeFromTop(12));content.removeFromTop(8);
    if(currentView==View::console){auto creative=content.removeFromTop(42);target.setBounds(creative.removeFromLeft(230));ceiling.setBounds(creative.removeFromLeft(230));width.setBounds(creative.removeFromLeft(230));saturationDrive.setBounds(creative.removeFromLeft(230));saturationMix.setBounds(creative.removeFromLeft(230));auto actions=content.removeFromTop(36);for(auto*b:{&chooseButton,&referenceButton,&clearReferenceButton,&analyseButton,&previewButton}){b->setBounds(actions.removeFromLeft(150).reduced(2,0));}cancelButton.setBounds(actions.removeFromLeft(120));content.removeFromTop(8);auto conversation=content.removeFromTop(38);doziPrompt.setBounds(conversation.removeFromLeft(juce::jmax(300,conversation.getWidth()-330)));conversation.removeFromLeft(6);doziApplyButton.setBounds(conversation.removeFromLeft(175));conversation.removeFromLeft(6);doziUndoButton.setBounds(conversation.removeFromLeft(140));content.removeFromTop(8);auto summaries=content;auto beforeArea=summaries.removeFromLeft(summaries.getWidth()/2);beforeSummary.setBounds(beforeArea.reduced(3));afterSummary.setBounds(summaries.reduced(3));}
    else if(currentView==View::wave){waveformView.setBounds(content);waveformView.setHorizontalInset(static_cast<float>(seek.getLookAndFeel().getSliderThumbRadius(seek)));}
    else if(currentView==View::chain){auto modules=content.removeFromTop(78);auto row1=modules.removeFromTop(36);for(auto*b:{&eq,&dynamicEq,&deEsser,&comp})b->setBounds(row1.removeFromLeft(row1.getWidth()/4).reduced(3));auto row2=modules.removeFromTop(36);for(auto*b:{&multiband,&saturation,&stereo,&limiter})b->setBounds(row2.removeFromLeft(row2.getWidth()/4).reduced(3));auto parameters=content.removeFromTop(42);width.setBounds(parameters.removeFromLeft(230));saturationDrive.setBounds(parameters.removeFromLeft(230));saturationMix.setBounds(parameters.removeFromLeft(230));moduleInspector.setBounds(content.reduced(0,8));}
    else {auto actions=content.removeFromTop(38);exportButton.setBounds(actions.removeFromLeft(180));actions.removeFromLeft(8);saveVersionButton.setBounds(actions.removeFromLeft(140));actions.removeFromLeft(6);restoreVersionButton.setBounds(actions.removeFromLeft(140));actions.removeFromLeft(6);compareVersionButton.setBounds(actions.removeFromLeft(150));detailsButton.setBounds(actions.removeFromRight(190));content.removeFromTop(8);results.setBounds(content);auto beforeArea=content.removeFromLeft(content.getWidth()/2);beforeSummary.setBounds(beforeArea.reduced(3));afterSummary.setBounds(content.reduced(3));}
}

void MasteringComponent::showView(View view){
    currentView=view;workflowLabel.setVisible(false);
    consoleViewButton.setToggleState(view==View::console,juce::dontSendNotification);waveViewButton.setToggleState(view==View::wave,juce::dontSendNotification);chainViewButton.setToggleState(view==View::chain,juce::dontSendNotification);deliverViewButton.setToggleState(view==View::deliver,juce::dontSendNotification);
    for(auto*component:std::array<juce::Component*,32>{&chooseButton,&referenceButton,&clearReferenceButton,&analyseButton,&previewButton,&exportButton,&cancelButton,&saveVersionButton,&restoreVersionButton,&compareVersionButton,&target,&ceiling,&width,&saturationDrive,&saturationMix,&eq,&dynamicEq,&deEsser,&comp,&multiband,&saturation,&stereo,&limiter,&doziPrompt,&doziApplyButton,&doziUndoButton,&beforeSummary,&afterSummary,&results,&detailsButton,&waveformView,&moduleInspector})component->setVisible(false);
    if(view==View::console){for(auto*component:std::array<juce::Component*,15>{&chooseButton,&referenceButton,&clearReferenceButton,&analyseButton,&previewButton,&target,&ceiling,&width,&saturationDrive,&saturationMix,&doziPrompt,&doziApplyButton,&doziUndoButton,&beforeSummary,&afterSummary})component->setVisible(true);cancelButton.setVisible(worker!=nullptr);}
    else if(view==View::wave)waveformView.setVisible(true);
    else if(view==View::chain){for(auto*component:std::array<juce::Component*,12>{&eq,&dynamicEq,&deEsser,&comp,&multiband,&saturation,&stereo,&limiter,&width,&saturationDrive,&saturationMix,&moduleInspector})component->setVisible(true);}
    else {for(auto*component:std::array<juce::Component*,5>{&exportButton,&saveVersionButton,&restoreVersionButton,&compareVersionButton,&detailsButton})component->setVisible(true);const auto details=detailsButton.getToggleState();results.setVisible(details);beforeSummary.setVisible(!details);afterSummary.setVisible(!details);}
    resized();repaint();
}
bool MasteringComponent::isInterestedInFileDrag(const juce::StringArray&f){return f.size()==1&&juce::File(f[0]).hasFileExtension("wav;wave;aif;aiff;flac;mp3");}void MasteringComponent::filesDropped(const juce::StringArray&f,int,int){load(juce::File(f[0]));}
void MasteringComponent::choose(){const auto start=source.existsAsFile()?source:juce::File{};chooser=std::make_unique<juce::FileChooser>("Choose stereo mix",start,"*");chooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles,[this](const auto&c){const auto file=c.getResult();if(!file.existsAsFile())return;if(auto reader=std::unique_ptr<juce::AudioFormatReader>(formats.createReaderFor(file))){load(file);return;}status.setText("That file is not readable audio. Choose WAV, AIFF, FLAC, or MP3.",juce::dontSendNotification);});}
void MasteringComponent::chooseReference(){const auto start=reference.existsAsFile()?reference:source.existsAsFile()?source.getParentDirectory():juce::File{};chooser=std::make_unique<juce::FileChooser>("Choose stereo mastering reference",start,"*");chooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles,[this](const auto&c){const auto file=c.getResult();if(!file.existsAsFile())return;if(auto reader=std::unique_ptr<juce::AudioFormatReader>(formats.createReaderFor(file))){reference=file;referenceStatus.setText("Reference: "+reference.getFileName()+(reference.hasFileExtension("mp3")?" - LOSSY MP3":""),juce::dontSendNotification);if(source.existsAsFile())analyse();return;}status.setText("That reference is not readable audio. Choose WAV, AIFF, FLAC, or MP3.",juce::dontSendNotification);});}
void MasteringComponent::clearReference(){if(worker){status.setText("Wait for the current analysis to finish before clearing the reference",juce::dontSendNotification);return;}reference=juce::File{};referenceAnalysis.reset();referenceStatus.setText("Reference: none - using Dozi rules",juce::dontSendNotification);if(source.existsAsFile())analyse();else status.setText("Reference cleared",juce::dontSendNotification);}
void MasteringComponent::loadTransport(const juce::File&f,bool processed){if(auto*r=formats.createReaderFor(f)){auto reader=std::make_unique<juce::AudioFormatReaderSource>(r,true);auto&t=processed?afterTransport:beforeTransport;t.setSource(reader.get(),0,nullptr,r->sampleRate);if(processed)afterReader=std::move(reader);else beforeReader=std::move(reader);}}
void MasteringComponent::load(const juce::File&f){source=f;mastered=juce::File{};exportedFile=juce::File{};if(previewIsTemporary&&previewFile.existsAsFile())previewFile.deleteFile();previewFile=juce::File{};previewIsTemporary=false;before.reset();referenceAnalysis.reset();after.reset();plan.reset();doziPlanHistory.clear();doziUndoButton.setEnabled(false);moduleInspector.setPlan(nullptr);beforeHealth.reset();afterHealth.reset();limiterMaximumGainReductionDb=0;limiterSafetyTrimDb=0;targetMasteredBlend.store(0.0f);currentMasteredBlend=0.0f;masteredPlaybackGain.store(1.0f);abButton.setToggleState(false,juce::dontSendNotification);abButton.setButtonText("Playback: Original");waveform.clear();playbackMeter.reset();if(auto r=std::unique_ptr<juce::AudioFormatReader>(formats.createReaderFor(f))){constexpr int points=2000;juce::AudioBuffer<float>b(1,1);for(int i=0;i<points;++i){r->read(&b,0,1,r->lengthInSamples*i/points,true,true);waveform.push_back(b.getSample(0,0));}}loadTransport(f,false);waveformView.setWaveform(waveform,beforeTransport.getLengthInSeconds());seek.setValue(0,juce::dontSendNotification);updateTransportTime(0);loopSelectionButton.setToggleState(false,juce::dontSendNotification);loopSelectionButton.setButtonText("Loop Selection");loopSelectionButton.setEnabled(false);const auto lossy=f.hasFileExtension("mp3");formatBadge.setVisible(lossy);formatBadge.setText(lossy?"LOSSY MP3 SOURCE - Master export remains lossless WAV":"",juce::dontSendNotification);status.setText(f.getFileName(),juce::dontSendNotification);analyseButton.setEnabled(true);previewButton.setEnabled(false);exportButton.setEnabled(false);saveProjectButton.setEnabled(true);saveVersionButton.setEnabled(false);compareVersionButton.setEnabled(false);playButton.setEnabled(true);abButton.setEnabled(false);results.clear();beforeSummary.setText("BEFORE\n\nClick Analyze + Plan",false);afterSummary.setText("AFTER\n\nRender Verified Master after analysis",false);repaint();}
void MasteringComponent::setBusy(bool b){chooseButton.setEnabled(!b);referenceButton.setEnabled(!b);stylePreset.setEnabled(!b);targetPreset.setEnabled(!b);target.setEnabled(!b);ceiling.setEnabled(!b);clearReferenceButton.setEnabled(!b&&reference.existsAsFile());analyseButton.setEnabled(!b&&source.existsAsFile());previewButton.setEnabled(!b&&plan.has_value());exportButton.setEnabled(!b&&plan.has_value());saveProjectButton.setEnabled(!b&&source.existsAsFile());openProjectButton.setEnabled(!b);saveVersionButton.setEnabled(!b&&plan.has_value());restoreVersionButton.setEnabled(!b);compareVersionButton.setEnabled(!b&&plan.has_value());cancelButton.setVisible(b);progressValue=b?-1:0;}
void MasteringComponent::cancel(){if(token)token->cancel();status.setText("Cancelling...",juce::dontSendNotification);}

void MasteringComponent::analyse(){
    if(worker)return;setBusy(true);token=std::make_shared<dozi::core::CancellationToken>();
    const auto path=source.getFullPathName().toStdString(),referencePath=reference.getFullPathName().toStdString();
    dozi::core::MasteringDecisionConfig config;config.targetIntegratedLufs=target.getValue();config.truePeakCeilingDbtp=ceiling.getValue();
    const auto presetId=targetPreset.getSelectedId();if(presetId>=1&&presetId<=3)config.targetId=std::array<std::string,3>{"spotify-normal","spotify-loud","spotify-quiet"}[static_cast<std::size_t>(presetId-1)];else config.targetId="custom";
    const auto styleIndex=stylePreset.getSelectedItemIndex();const auto&styles=dozi::core::factoryMasteringStyles();const auto styleId=styleIndex>=0&&styleIndex<static_cast<int>(styles.size())?styles[static_cast<std::size_t>(styleIndex)].id:std::string("balanced-streaming");
    worker=std::make_unique<std::thread>([this,path,referencePath,config,styleId,t=token]{
        AnalysisJobResult job;const auto sourceResult=dozi::core::MasteringAnalyzer{}.analyse(path,*t);
        if(sourceResult.result){job.source=*sourceResult.result;if(!referencePath.empty()){const auto referenceResult=dozi::core::MasteringAnalyzer{}.analyse(referencePath,*t);if(!referenceResult.result)job.error=referenceResult.error?referenceResult.error->message:"Reference analysis cancelled";else if(referenceResult.result->sampleRateHz!=job.source->sampleRateHz)job.error="Reference sample rate does not match the mix";else if(referenceResult.result->channelCount!=2)job.error="Reference must be stereo";else job.reference=*referenceResult.result;}if(job.error.isEmpty()&&!t->isCancelled()){job.plan=dozi::core::MasteringReferenceMatcher{}.createPhase2Plan(*job.source,job.reference,config);if(const auto*style=dozi::core::masteringStyle(styleId))dozi::core::applyMasteringStyle(*job.plan,*job.source,*style);job.health=dozi::core::MasteringHealthScorer{}.score(*job.source,healthConfig(*job.plan,job.reference));}}else job.error=sourceResult.error?sourceResult.error->message:"Analysis cancelled";
        juce::MessageManager::callAsync([this,job=std::move(job)]{if(job.plan){before=job.source;referenceAnalysis=job.reference;plan=job.plan;beforeHealth=job.health;applyPlanToControls(*plan);moduleInspector.setPlan(&*plan);refreshText();status.setText(reference.existsAsFile()?"Mix and reference analysis complete":"Analysis complete",juce::dontSendNotification);}else status.setText(job.error.isNotEmpty()?job.error:"Analysis cancelled",juce::dontSendNotification);if(worker->joinable())worker->join();worker.reset();token.reset();setBusy(false);});
    });
}

void MasteringComponent::renderPreview(){
    if(!plan||worker)return;
    if(previewIsTemporary&&previewFile.existsAsFile())previewFile.deleteFile();
    previewFile=juce::File::getSpecialLocation(juce::File::tempDirectory)
        .getNonexistentChildFile("Dozi-Mastering-Preview",".wav",false);
    previewIsTemporary=true;
    const auto selected=planFromControls();
    const auto out=previewFile;
    setBusy(true);token=std::make_shared<dozi::core::CancellationToken>();status.setText("Rendering preview...",juce::dontSendNotification);
    worker=std::make_unique<std::thread>([this,selected,out,t=token]{try{
        auto r=dozi::core::MasteringRenderer{}.render(source.getFullPathName().toStdString(),out.getFullPathName().toStdString(),selected,*t,true,[safe=juce::Component::SafePointer<MasteringComponent>(this)](const dozi::core::ProcessorTelemetry&measured){juce::MessageManager::callAsync([safe,measured]{if(safe)safe->moduleInspector.updateTelemetry(measured);});});
        juce::MessageManager::callAsync([this,out,selected,r=std::move(r)]{
            plan=selected;mastered=out;after=r.after;afterHealth=dozi::core::MasteringHealthScorer{}.score(*after,healthConfig(*plan,referenceAnalysis));moduleInspector.setTelemetry(r.telemetry);limiterMaximumGainReductionDb=r.limiterMaximumGainReductionDb;limiterSafetyTrimDb=r.limiterSafetyTrimDb;const auto position=beforeTransport.getCurrentPosition();const auto playing=beforeTransport.isPlaying();loadTransport(out,true);afterTransport.setPosition(position);if(playing)afterTransport.start();abButton.setEnabled(true);abButton.setToggleState(true,juce::dontSendNotification);switchAB();updatePlaybackGain();refreshText();status.setText("Preview rendered - playback is Mastered",juce::dontSendNotification);if(worker->joinable())worker->join();worker.reset();token.reset();setBusy(false);
        });
    }catch(const std::exception&e){const juce::String m=e.what();juce::MessageManager::callAsync([this,m]{status.setText("Preview stopped: "+m,juce::dontSendNotification);if(worker->joinable())worker->join();worker.reset();token.reset();setBusy(false);});}});
}

dozi::core::MasteringPlan MasteringComponent::planFromControls()const{
    auto selected=*plan;selected.targetIntegratedLufs=target.getValue();selected.truePeakCeilingDbtp=ceiling.getValue();
    const auto styleIndex=stylePreset.getSelectedItemIndex();const auto&styles=dozi::core::factoryMasteringStyles();if(styleIndex>=0&&styleIndex<static_cast<int>(styles.size()))selected.styleId=styles[static_cast<std::size_t>(styleIndex)].id;
    const auto presetId=targetPreset.getSelectedId();selected.targetId=presetId>=1&&presetId<=3?std::array<std::string,3>{"spotify-normal","spotify-loud","spotify-quiet"}[static_cast<std::size_t>(presetId-1)]:"custom";
    for(auto& module:selected.modules){if(module.type==Type::linearPhaseEq)module.bypassed=!eq.getToggleState();else if(module.type==Type::dynamicEq)module.bypassed=!dynamicEq.getToggleState();else if(module.type==Type::deEsser)module.bypassed=!deEsser.getToggleState();else if(module.type==Type::broadbandCompressor)module.bypassed=!comp.getToggleState();else if(module.type==Type::multibandCompressor)module.bypassed=!multiband.getToggleState();else if(module.type==Type::saturation){module.bypassed=!saturation.getToggleState();module.parameters["driveDb"]=saturationDrive.getValue();module.parameters["mix"]=saturationMix.getValue();}else if(module.type==Type::stereoWidthMonoBass){module.bypassed=!stereo.getToggleState();module.parameters["widthFactor"]=width.getValue();}else if(module.type==Type::truePeakLimiter){module.bypassed=!limiter.getToggleState();module.parameters["ceilingDbtp"]=selected.truePeakCeilingDbtp;module.parameters["lookaheadMs"]=5.0;}}
    return selected;
}

void MasteringComponent::applyPlanToControls(const dozi::core::MasteringPlan& value){
    target.setValue(value.targetIntegratedLufs,juce::dontSendNotification);ceiling.setValue(value.truePeakCeilingDbtp,juce::dontSendNotification);
    const auto&styles=dozi::core::factoryMasteringStyles();const auto style=std::ranges::find(styles,value.styleId,&dozi::core::MasteringStylePreset::id);stylePreset.setSelectedItemIndex(style==styles.end()?1:static_cast<int>(std::distance(styles.begin(),style)),juce::dontSendNotification);
    const std::array ids{"spotify-normal","spotify-loud","spotify-quiet"};const auto found=std::find(ids.begin(),ids.end(),value.targetId);targetPreset.setSelectedId(found==ids.end()?4:static_cast<int>(std::distance(ids.begin(),found))+1,juce::dontSendNotification);
    for(const auto& module:value.modules){const auto enabled=!module.bypassed;if(module.type==Type::linearPhaseEq)eq.setToggleState(enabled,juce::dontSendNotification);else if(module.type==Type::dynamicEq)dynamicEq.setToggleState(enabled,juce::dontSendNotification);else if(module.type==Type::deEsser)deEsser.setToggleState(enabled,juce::dontSendNotification);else if(module.type==Type::broadbandCompressor)comp.setToggleState(enabled,juce::dontSendNotification);else if(module.type==Type::multibandCompressor)multiband.setToggleState(enabled,juce::dontSendNotification);else if(module.type==Type::saturation){saturation.setToggleState(enabled,juce::dontSendNotification);if(module.parameters.contains("driveDb"))saturationDrive.setValue(module.parameters.at("driveDb"),juce::dontSendNotification);if(module.parameters.contains("mix"))saturationMix.setValue(module.parameters.at("mix"),juce::dontSendNotification);}else if(module.type==Type::stereoWidthMonoBass){stereo.setToggleState(enabled,juce::dontSendNotification);if(module.parameters.contains("widthFactor"))width.setValue(module.parameters.at("widthFactor"),juce::dontSendNotification);}else if(module.type==Type::truePeakLimiter)limiter.setToggleState(enabled,juce::dontSendNotification);}
}

void MasteringComponent::refreshText(){
    if(!before||!plan||!beforeHealth)return;
    const auto summary=[](const juce::String&heading,const dozi::core::MasteringAnalysisResult&analysis,const dozi::core::MasteringHealthScore&health){juce::String text=heading+"\n\nIntegrated loudness\n  "+juce::String(analysis.integratedLufs,2)+" LUFS\n\nTrue peak\n  "+juce::String(analysis.truePeakDbtp,2)+" dBTP\n\nRMS\n  "+juce::String(analysis.rmsDbfs,2)+" dBFS\n\nCrest factor\n  "+juce::String(analysis.crestFactorDb,2)+" dB\n\n";for(const auto&category:health.categories)text+=juce::String(category.name)+"\n  "+juce::String(category.score,2)+" / 100\n\n";text+="Overall Health\n  "+juce::String(health.overall,2)+" / 100\n";return text;};
    const auto diagnoses=dozi::core::MasteringDiagnosticEngine{}.diagnose(*before,referenceAnalysis);juce::String diagnosticSummary="\nDIAGNOSTIC HYPOTHESES\n";if(diagnoses.empty())diagnosticSummary+="  No measured outliers crossed the conservative diagnostic thresholds.\n";for(const auto&finding:diagnoses){diagnosticSummary+="\n"+juce::String(finding.descriptor)+"  ["+juce::String(juce::roundToInt(finding.strength*100.0))+"% evidence strength]\n"+juce::String(finding.evidence)+"\nRecommendation: "+juce::String(finding.recommendation)+"\n";if(finding.returnToMixRecommended)diagnosticSummary+="Mix revision recommended.\n";}
    beforeSummary.setText(summary("BEFORE",*before,*beforeHealth)+diagnosticSummary,false);
    if(after&&afterHealth)afterSummary.setText(summary("AFTER",*after,*afterHealth)+"\nLimiter gain reduction\n  "+juce::String(limiterMaximumGainReductionDb,2)+" dB\n",false);else afterSummary.setText("AFTER\n\nRender Preview to calculate the mastered measurements.",false);
    juce::String technical="TECHNICAL DETAILS\n\n"+juce::String(dozi::core::MasteringReport::text(*before,*plan,*beforeHealth))+"\nPERCEPTUAL DIAGNOSTICS\n"+diagnosticSummary;
    if(reference.existsAsFile())technical+="\nReference: "+reference.getFileName()+"\nTonal scoring uses the measured reference curve.\n";
    if(!before->resonances.empty()){technical+="\nRESONANCES\n";for(const auto&resonance:before->resonances)technical+=juce::String(resonance.frequencyHz,1)+" Hz, "+juce::String(resonance.excessDb,2)+" dB above local average\n";}
    technical+="\nDECISION TRACE\n";for(std::size_t index=0;index<plan->modules.size();++index){technical+="\nModule "+juce::String(static_cast<int>(index)+1)+(plan->modules[index].bypassed?" (bypassed)":" (enabled)")+"\n";for(const auto&reason:plan->modules[index].reasons)technical+=juce::String(reason.ruleId)+": measured "+juce::String(reason.measuredValue,2)+" "+reason.unit+" - "+reason.action+"\n";for(const auto&[key,value]:plan->modules[index].parameters)technical+=juce::String(key)+" = "+juce::String(value,4)+"\n";}
    if(after&&afterHealth){technical+="\nAFTER SCORE CONTRIBUTIONS\n";for(const auto&category:afterHealth->categories)for(const auto&component:category.components)technical+=juce::String(category.name)+" / "+component.measurement+": measured "+juce::String(component.value,2)+", score "+juce::String(component.contribution,2)+"/100\n";technical+="\nLimiter maximum gain reduction: "+juce::String(limiterMaximumGainReductionDb,2)+" dB\nLimiter final true-peak safety trim: "+juce::String(limiterSafetyTrimDb,2)+" dB\n";}
    results.setText(technical,false);
}
void MasteringComponent::switchAB(){targetMasteredBlend.store(abButton.getToggleState()?1.0f:0.0f);abButton.setButtonText(abButton.getToggleState()?"Playback: Mastered":"Playback: Original");status.setText(abButton.getToggleState()?"Mastered playback":"Original playback",juce::dontSendNotification);}
void MasteringComponent::updatePlaybackGain(){const auto gain=before&&after&&loudnessMatchButton.getToggleState()?static_cast<float>(std::pow(10.0,(before->integratedLufs-after->integratedLufs)/20.0)):1.0f;masteredPlaybackGain.store(gain);status.setText(loudnessMatchButton.getToggleState()?"Loudness matching enabled":"Loudness matching disabled",juce::dontSendNotification);}
void MasteringComponent::updateMonitorGain(){monitorGain.store(monitorMuteButton.getToggleState()?0.0f:juce::Decibels::decibelsToGain(static_cast<float>(monitorLevel.getValue()),-60.0f));monitorMuteButton.setButtonText(monitorMuteButton.getToggleState()?"Muted":"Mute");}
void MasteringComponent::togglePlayback(){if(beforeTransport.isPlaying()||afterTransport.isPlaying()){beforeTransport.stop();afterTransport.stop();playButton.setButtonText("Play");}else{const auto position=beforeTransport.getCurrentPosition();afterTransport.setPosition(position);beforeTransport.start();afterTransport.start();playButton.setButtonText("Pause");}}
void MasteringComponent::seekBoth(double seconds){const auto length=beforeTransport.getLengthInSeconds();const auto position=std::clamp(seconds,0.0,std::max(0.0,length));beforeTransport.setPosition(position);afterTransport.setPosition(position);if(length>0)seek.setValue(position/length,juce::dontSendNotification);waveformView.setPlayhead(position);updateTransportTime(position);}
void MasteringComponent::updateTransportTime(double seconds){const auto format=[](double value){value=std::max(0.0,value);const auto whole=static_cast<int>(std::floor(value));return juce::String(whole/60)+":"+juce::String(whole%60).paddedLeft('0',2);};transportTime.setText(format(seconds)+" / "+format(beforeTransport.getLengthInSeconds()),juce::dontSendNotification);}
void MasteringComponent::nudgePlayback(double seconds){seekBoth(beforeTransport.getCurrentPosition()+seconds);status.setText(seconds<0?"Playhead moved left 1 second":"Playhead moved right 1 second",juce::dontSendNotification);}
void MasteringComponent::updateLoopControls(double startSeconds,double endSeconds){const auto valid=endSeconds-startSeconds>=0.02;loopSelectionButton.setEnabled(valid);if(!valid){loopSelectionButton.setToggleState(false,juce::dontSendNotification);loopSelectionButton.setButtonText("Loop Selection");return;}const auto time=[](double seconds){const auto minutes=static_cast<int>(seconds)/60;return juce::String(minutes)+":"+juce::String(std::fmod(seconds,60.0),1).paddedLeft('0',4);};loopSelectionButton.setButtonText("Loop "+time(startSeconds)+" - "+time(endSeconds));}
void MasteringComponent::submitDoziRequest(){if(worker){status.setText("Wait for the current render before requesting another change",juce::dontSendNotification);return;}if(!plan||!before){status.setText("Analyze the mix before asking Dozi for mastering changes",juce::dontSendNotification);return;}const auto request=doziPrompt.getText().trim().toLowerCase();if(request.isEmpty())return;if(request.contains("undo")){undoDoziRequest();doziPrompt.clear();return;}const auto lowEnd=request.contains("bass")||request.contains("low end")||request.contains("low-end")||request.contains("80 hz")||request.contains("80hz");const auto followup=request.contains("little more")||request.contains("a bit more");const auto reduce=request.contains("less")||request.contains("reduce")||request.contains("lower")||request.contains("too much")||followup;if((lowEnd||followup)&&reduce){applyLowEndAdjustment(followup?-0.25:-0.5);doziPrompt.clear();return;}status.setText("Dozi currently understands requests to reduce bass/low end and 'a little more'",juce::dontSendNotification);}
void MasteringComponent::applyLowEndAdjustment(double amountDb){if(!plan||!before)return;const auto found=std::ranges::find(plan->modules,Type::linearPhaseEq,&dozi::core::MasteringModulePlan::type);if(found==plan->modules.end())return;doziPlanHistory.push_back(*plan);if(doziPlanHistory.size()>20)doziPlanHistory.erase(doziPlanHistory.begin());auto&module=*found;module.bypassed=false;module.parameters["assistantLowEnd.frequencyHz"]=80.0;module.parameters["assistantLowEnd.q"]=0.7;const auto previous=module.parameters.contains("assistantLowEnd.gainDb")?module.parameters["assistantLowEnd.gainDb"]:0.0;const auto adjusted=std::clamp(previous+amountDb,-3.0,0.0);module.parameters["assistantLowEnd.gainDb"]=adjusted;module.reasons.push_back({"conversational low-end adjustment",adjusted,"dB","DOZI_ASSISTANT_LOW_END","broad linear-phase cut centered at 80 Hz","Apply listener-requested low-end reduction"});applyPlanToControls(*plan);moduleInspector.setPlan(&*plan);refreshText();doziUndoButton.setEnabled(true);status.setText("Dozi reduced the low end at 80 Hz to "+juce::String(adjusted,2)+" dB - click Render Preview to apply",juce::dontSendNotification);}
void MasteringComponent::undoDoziRequest(){if(worker){status.setText("Wait for the current render before undoing",juce::dontSendNotification);return;}if(doziPlanHistory.empty()){status.setText("There is no Dozi adjustment to undo",juce::dontSendNotification);return;}plan=std::move(doziPlanHistory.back());doziPlanHistory.pop_back();applyPlanToControls(*plan);moduleInspector.setPlan(&*plan);refreshText();doziUndoButton.setEnabled(!doziPlanHistory.empty());status.setText("Dozi adjustment undone - click Render Preview to apply",juce::dontSendNotification);}
void MasteringComponent::installTransportKeyListeners(juce::Component&parent){for(auto*child:parent.getChildren()){child->addKeyListener(this);installTransportKeyListeners(*child);}}
bool MasteringComponent::handleTransportShortcut(const juce::KeyPress&key){if(juce::Component::getCurrentlyFocusedComponent()==&doziPrompt)return false;if(key.getKeyCode()==juce::KeyPress::spaceKey){if(playButton.isEnabled())togglePlayback();return true;}if(key.getKeyCode()==juce::KeyPress::returnKey){seekBoth(0);status.setText("Returned to beginning",juce::dontSendNotification);return true;}return false;}
bool MasteringComponent::keyPressed(const juce::KeyPress&key,juce::Component*){if(handleTransportShortcut(key))return true;if(dynamic_cast<juce::TextEditor*>(juce::Component::getCurrentlyFocusedComponent())!=nullptr)return false;const auto character=key.getTextCharacter();if(character=='<'||character==','){nudgePlayback(-1.0);return true;}if(character=='>'||character=='.'){nudgePlayback(1.0);return true;}return false;}

void MasteringComponent::saveProject(){
    if(!source.existsAsFile())return;
    chooser=std::make_unique<juce::FileChooser>("Save Dozi mastering project",source.getSiblingFile(source.getFileNameWithoutExtension()+".doziproject"),"*.doziproject");
    chooser->launchAsync(juce::FileBrowserComponent::saveMode|juce::FileBrowserComponent::warnAboutOverwriting,[this](const auto&c){const auto file=c.getResult();if(file==juce::File{})return;if(previewIsTemporary&&previewFile.existsAsFile()){const auto persistent=file.withFileExtension("preview.wav");persistent.deleteFile();if(!previewFile.copyFileTo(persistent)){status.setText("Could not preserve the rendered project preview",juce::dontSendNotification);return;}previewFile.deleteFile();previewFile=persistent;previewIsTemporary=false;}const auto error=dozi::core::MasteringProjectStore{}.save(file.getFullPathName().toStdString(),currentProject());if(error.empty())addRecentSession(file);status.setText(error.empty()?"Project saved - source audio remains referenced, not copied":juce::String(error),juce::dontSendNotification);});
}

void MasteringComponent::openProject(){
    chooser=std::make_unique<juce::FileChooser>("Open Dozi mastering project",juce::File{},"*.doziproject");
    chooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles,[this](const auto&c){const auto file=c.getResult();if(file.existsAsFile())openProjectFile(file);});
}

void MasteringComponent::openProjectFile(const juce::File&file){const auto outcome=dozi::core::MasteringProjectStore{}.open(file.getFullPathName().toStdString());if(!outcome.project){status.setText(outcome.error,juce::dontSendNotification);return;}auto project=*outcome.project;if(juce::File(project.sourcePath.string()).existsAsFile()){applyProject(std::move(project));addRecentSession(file);return;}chooser=std::make_unique<juce::FileChooser>("The source mix moved - locate it",juce::File{},"*");chooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles,[this,file,project=std::move(project)](const auto&relocation)mutable{const auto replacement=relocation.getResult();if(!replacement.existsAsFile()){status.setText("Project open cancelled: source mix was not located",juce::dontSendNotification);return;}if(!std::unique_ptr<juce::AudioFormatReader>(formats.createReaderFor(replacement))){status.setText("The replacement is not readable audio",juce::dontSendNotification);return;}project.sourcePath=replacement.getFullPathName().toStdString();if(project.sourceAnalysis)project.sourceAnalysis->path=project.sourcePath;applyProject(std::move(project));addRecentSession(file);});}

dozi::core::MasteringProject MasteringComponent::currentProject(const juce::File&previewOverride)const{dozi::core::MasteringProject project;project.sourcePath=source.getFullPathName().toStdString();project.referencePath=reference.getFullPathName().toStdString();const auto savedPreview=previewOverride==juce::File{}?previewFile:previewOverride;project.previewPath=savedPreview.getFullPathName().toStdString();project.exportPath=exportedFile.getFullPathName().toStdString();const auto&t=abButton.getToggleState()?afterTransport:beforeTransport;project.playbackPositionSeconds=t.getCurrentPosition();project.playbackMastered=abButton.getToggleState();project.loudnessMatched=loudnessMatchButton.getToggleState();project.selectionStartSeconds=waveformView.selectionStartSeconds();project.selectionEndSeconds=waveformView.selectionEndSeconds();project.loopSelectionEnabled=loopSelectionButton.getToggleState()&&waveformView.hasSelection();project.sourceAnalysis=before;project.referenceAnalysis=referenceAnalysis;project.processedAnalysis=after;if(plan)project.plan=planFromControls();return project;}

juce::File MasteringComponent::sessionSupportDirectory()const{return juce::File::getSpecialLocation(juce::File::userApplicationDataDirectory).getChildFile("Dozi").getChildFile("Dozi Mastering");}
void MasteringComponent::saveRecoverySession(){
    if(!source.existsAsFile())return;
    const auto directory=sessionSupportDirectory();if(!directory.createDirectory())return;
    juce::File savedPreview;
    if(previewFile.existsAsFile()){
        savedPreview=directory.getChildFile("Last Session Preview.wav");
        if(previewFile!=savedPreview){const auto temporary=directory.getChildFile("Last Session Preview.partial.wav");temporary.deleteFile();if(!previewFile.copyFileTo(temporary)||!temporary.replaceFileIn(savedPreview)){temporary.deleteFile();savedPreview=juce::File{};}}
    }
    const auto recovery=directory.getChildFile("Last Session.doziproject");
    const auto error=dozi::core::MasteringProjectStore{}.save(recovery.getFullPathName().toStdString(),currentProject(savedPreview));
    if(!error.empty())juce::Logger::writeToLog("Could not save Dozi Mastering recovery session: "+juce::String(error));
}
void MasteringComponent::restoreRecoverySession(){const auto file=sessionSupportDirectory().getChildFile("Last Session.doziproject");if(!file.existsAsFile())return;const auto outcome=dozi::core::MasteringProjectStore{}.open(file.getFullPathName().toStdString());if(!outcome.project||!juce::File(outcome.project->sourcePath.string()).existsAsFile())return;applyProject(*outcome.project);status.setText("Last mastering session restored",juce::dontSendNotification);}
void MasteringComponent::loadRecentSessions(){recentSessions.clear();juce::StringArray lines;sessionSupportDirectory().getChildFile("Recent Sessions.txt").readLines(lines);for(const auto&line:lines){juce::File file(line);if(file.existsAsFile()&&file.hasFileExtension("doziproject"))recentSessions.push_back(file);}recentProjectsButton.setEnabled(!recentSessions.empty());}
void MasteringComponent::addRecentSession(const juce::File&file){const auto full=file.getFullPathName();std::erase_if(recentSessions,[&](const auto&entry){return entry.getFullPathName()==full;});recentSessions.insert(recentSessions.begin(),file);if(recentSessions.size()>10)recentSessions.resize(10);const auto directory=sessionSupportDirectory();directory.createDirectory();juce::String text;for(const auto&entry:recentSessions)text<<entry.getFullPathName()<<"\n";directory.getChildFile("Recent Sessions.txt").replaceWithText(text);recentProjectsButton.setEnabled(true);}
void MasteringComponent::showRecentSessions(){juce::PopupMenu menu;if(recentSessions.empty()){menu.addItem(1,"No recent sessions",false,false);}else{for(std::size_t index=0;index<recentSessions.size();++index){const auto&file=recentSessions[index];menu.addItem(static_cast<int>(index)+1,file.getFileNameWithoutExtension()+" - "+file.getParentDirectory().getFullPathName());}}menu.showMenuAsync(juce::PopupMenu::Options{}.withTargetComponent(&recentProjectsButton),[safe=juce::Component::SafePointer<MasteringComponent>(this)](int result){if(safe&&result>0&&result<=static_cast<int>(safe->recentSessions.size()))safe->openProjectFile(safe->recentSessions[static_cast<std::size_t>(result-1)]);});}

void MasteringComponent::applyProject(dozi::core::MasteringProject project){
    const juce::File projectSource(project.sourcePath.string());load(projectSource);
    reference=juce::File(project.referencePath.string());referenceStatus.setText(reference.existsAsFile()?"Reference: "+reference.getFileName():project.referencePath.empty()?"Reference: none":"Reference missing - choose it again",juce::dontSendNotification);
    before=std::move(project.sourceAnalysis);referenceAnalysis=std::move(project.referenceAnalysis);after=std::move(project.processedAnalysis);plan=std::move(project.plan);previewFile=juce::File(project.previewPath.string());previewIsTemporary=false;exportedFile=juce::File(project.exportPath.string());
    const auto playable=exportedFile.existsAsFile()?exportedFile:previewFile.existsAsFile()?previewFile:juce::File{};if(playable.existsAsFile()){mastered=playable;loadTransport(playable,true);abButton.setEnabled(after.has_value());}
    if(plan){applyPlanToControls(*plan);moduleInspector.setPlan(&*plan);if(before){const auto config=healthConfig(*plan,referenceAnalysis);beforeHealth=dozi::core::MasteringHealthScorer{}.score(*before,config);if(after)afterHealth=dozi::core::MasteringHealthScorer{}.score(*after,config);refreshText();}}
    const auto canPlayMastered=playable.existsAsFile()&&after.has_value();abButton.setToggleState(project.playbackMastered&&canPlayMastered,juce::dontSendNotification);loudnessMatchButton.setToggleState(project.loudnessMatched,juce::dontSendNotification);waveformView.setSelection(project.selectionStartSeconds,project.selectionEndSeconds);updateLoopControls(project.selectionStartSeconds,project.selectionEndSeconds);loopSelectionButton.setToggleState(project.loopSelectionEnabled&&waveformView.hasSelection(),juce::dontSendNotification);seekBoth(project.playbackPositionSeconds);currentMasteredBlend=abButton.getToggleState()?1.0f:0.0f;switchAB();updatePlaybackGain();setBusy(false);status.setText(canPlayMastered?"Project restored with mastered playback":"Project restored - render preview to recreate mastered playback",juce::dontSendNotification);
}

void MasteringComponent::saveVersion(){if(!plan)return;chooser=std::make_unique<juce::FileChooser>("Save mastering version",source.getSiblingFile(source.getFileNameWithoutExtension()+".dozimaster"),"*.dozimaster");chooser->launchAsync(juce::FileBrowserComponent::saveMode|juce::FileBrowserComponent::warnAboutOverwriting,[this](const auto& c){const auto file=c.getResult();if(file==juce::File{})return;const auto error=dozi::core::MasteringVersionStore{}.save(file.getFullPathName().toStdString(),planFromControls());status.setText(error.empty()?"Mastering version saved":juce::String(error),juce::dontSendNotification);});}
void MasteringComponent::restoreVersion(){chooser=std::make_unique<juce::FileChooser>("Restore mastering version",juce::File{},"*.dozimaster");chooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles,[this](const auto& c){const auto restored=dozi::core::MasteringVersionStore{}.restore(c.getResult().getFullPathName().toStdString());if(!restored.plan){status.setText(restored.error,juce::dontSendNotification);return;}plan=*restored.plan;applyPlanToControls(*plan);moduleInspector.setPlan(&*plan);if(before&&beforeHealth)refreshText();status.setText("Mastering version restored",juce::dontSendNotification);setBusy(false);});}
void MasteringComponent::compareVersion(){if(!plan)return;chooser=std::make_unique<juce::FileChooser>("Compare mastering version",juce::File{},"*.dozimaster");chooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles,[this](const auto& c){const auto restored=dozi::core::MasteringVersionStore{}.restore(c.getResult().getFullPathName().toStdString());if(!restored.plan){status.setText(restored.error,juce::dontSendNotification);return;}const auto differences=dozi::core::MasteringVersionStore{}.compare(planFromControls(),*restored.plan);juce::String text="VERSION COMPARISON\n";if(differences.empty())text+="No plan differences.";for(const auto& difference:differences){text+="\n"+juce::String(difference.path);if(!difference.leftText.empty()||!difference.rightText.empty())text+=": "+juce::String(difference.leftText)+" -> "+juce::String(difference.rightText);else{text+=": ";text+=difference.leftValue?juce::String(*difference.leftValue,6):"missing";text+=" -> ";text+=difference.rightValue?juce::String(*difference.rightValue,6):"missing";}}results.setReadOnly(true);results.setText(text);status.setText(juce::String(static_cast<int>(differences.size()))+" version differences",juce::dontSendNotification);});}

void MasteringComponent::exportMaster(){
    if(!plan||worker)return;auto*dialog=new juce::AlertWindow("Export Master","Choose the delivery format. MP3 is encoded from the verified lossless master.",juce::AlertWindow::NoIcon);
    dialog->addComboBox("format",{"WAV - 32-bit float","MP3 - constant bitrate"},"Format");dialog->getComboBoxComponent("format")->setSelectedItemIndex(0);
    dialog->addComboBox("bitrate",{"32 kbps","40 kbps","48 kbps","56 kbps","64 kbps","80 kbps","96 kbps","112 kbps","128 kbps","160 kbps","192 kbps","224 kbps","256 kbps","320 kbps"},"MP3 bitrate");dialog->getComboBoxComponent("bitrate")->setSelectedItemIndex(13);
    dialog->addButton("Continue",1,juce::KeyPress(juce::KeyPress::returnKey));dialog->addButton("Cancel",0,juce::KeyPress(juce::KeyPress::escapeKey));
    dialog->enterModalState(true,juce::ModalCallbackFunction::create([this,dialog](int result){if(result==0)return;constexpr std::array rates{32,40,48,56,64,80,96,112,128,160,192,224,256,320};const auto mp3=dialog->getComboBoxComponent("format")->getSelectedItemIndex()==1;const auto index=juce::jlimit(0,13,dialog->getComboBoxComponent("bitrate")->getSelectedItemIndex());exportMasterTo(mp3,rates[static_cast<std::size_t>(index)]);}),true);
}

void MasteringComponent::exportMasterTo(bool mp3,int bitRateKbps,bool createNew){
    const juce::String extension=mp3?"mp3":"wav";
    if(!createNew&&exportedFile.existsAsFile()&&exportedFile.hasFileExtension(extension)){
        auto*dialog=new juce::AlertWindow("Export Destination","Replace the current "+extension.toUpperCase()+" export or create a separate file?\n\nCurrent: "+exportedFile.getFullPathName(),juce::AlertWindow::QuestionIcon);
        dialog->addButton("Replace Current Export",1);dialog->addButton("Create New File",2);dialog->addButton("Cancel",0,juce::KeyPress(juce::KeyPress::escapeKey));
        dialog->enterModalState(true,juce::ModalCallbackFunction::create([this,mp3,bitRateKbps](int result){if(result==1)renderExportTo(exportedFile,mp3,bitRateKbps);else if(result==2)exportMasterTo(mp3,bitRateKbps,true);}),true);return;
    }
    const auto suffix=mp3?".mp3":".wav";chooser=std::make_unique<juce::FileChooser>(mp3?"Create new mastered MP3":"Create new mastered WAV",source.getSiblingFile(source.getFileNameWithoutExtension()+"-DoziMaster"+suffix),mp3?"*.mp3":"*.wav");
    chooser->launchAsync(juce::FileBrowserComponent::saveMode|juce::FileBrowserComponent::warnAboutOverwriting,[this,mp3,bitRateKbps](const auto&c){const auto out=c.getResult();if(out!=juce::File{})renderExportTo(out,mp3,bitRateKbps);});
}

void MasteringComponent::renderExportTo(const juce::File&out,bool mp3,int bitRateKbps){
    if(out==source){status.setText("The original mix cannot be replaced by an export. Choose a different destination.",juce::dontSendNotification);return;}
    const auto selected=planFromControls();setBusy(true);token=std::make_shared<dozi::core::CancellationToken>();worker=std::make_unique<std::thread>([this,selected,out,mp3,bitRateKbps,t=token]{juce::File renderedFile=out;try{
        if(mp3)renderedFile=juce::File::getSpecialLocation(juce::File::tempDirectory).getNonexistentChildFile("Dozi-MP3-Source",".wav",false);
        auto r=dozi::core::MasteringRenderer{}.render(source.getFullPathName().toStdString(),renderedFile.getFullPathName().toStdString(),selected,*t);
        if(mp3){const auto encoded=dozi::core::MasteringMp3Encoder{}.encode(renderedFile.getFullPathName().toStdString(),out.getFullPathName().toStdString(),bitRateKbps,*t);(void)encoded;renderedFile.deleteFile();}
        juce::MessageManager::callAsync([this,out,selected,mp3,bitRateKbps,r=std::move(r)]{plan=selected;mastered=out;exportedFile=out;after=r.after;afterHealth=dozi::core::MasteringHealthScorer{}.score(*after,healthConfig(*plan,referenceAnalysis));moduleInspector.setTelemetry(r.telemetry);limiterMaximumGainReductionDb=r.limiterMaximumGainReductionDb;limiterSafetyTrimDb=r.limiterSafetyTrimDb;out.withFileExtension("txt").replaceWithText(dozi::core::MasteringReport::text(*after,*plan,*afterHealth));out.withFileExtension("json").replaceWithText(dozi::core::MasteringReport::json(*after,*plan,*afterHealth));const auto position=beforeTransport.getCurrentPosition();const auto playing=beforeTransport.isPlaying();loadTransport(out,true);afterTransport.setPosition(position);if(playing)afterTransport.start();abButton.setEnabled(true);abButton.setToggleState(true,juce::dontSendNotification);switchAB();updatePlaybackGain();refreshText();status.setText(mp3?"MP3 "+juce::String(bitRateKbps)+" kbps exported and verified":"Lossless master and reports exported and verified",juce::dontSendNotification);if(worker->joinable())worker->join();worker.reset();token.reset();setBusy(false);});
    }catch(const std::exception&e){if(mp3)renderedFile.deleteFile();const juce::String m=e.what();juce::MessageManager::callAsync([this,m]{status.setText("Export stopped: "+m,juce::dontSendNotification);if(worker->joinable())worker->join();worker.reset();token.reset();setBusy(false);});}});
}

void MasteringComponent::timerCallback(){installTransportKeyListeners(*this);auto&t=abButton.getToggleState()?afterTransport:beforeTransport;auto position=t.getCurrentPosition();const auto length=t.getLengthInSeconds();auto playing=t.isPlaying();if(loopSelectionButton.getToggleState()&&waveformView.hasSelection()&&position>=waveformView.selectionEndSeconds()){seekBoth(waveformView.selectionStartSeconds());position=waveformView.selectionStartSeconds();if(playbackWasRunning){beforeTransport.start();afterTransport.start();playing=true;}}else if(playbackWasRunning&&!playing&&length>0&&position>=length-.05){seekBoth(0);position=0;if(loopTrackButton.getToggleState()){beforeTransport.start();afterTransport.start();playing=true;}else playButton.setButtonText("Play");}if(!seek.isMouseButtonDown()&&length>0)seek.setValue(position/length,juce::dontSendNotification);waveformView.setPlayhead(position);updateTransportTime(position);if(!playing)playbackMeter.reset();else playbackMeter.repaint();playbackWasRunning=playing;}
