#include "MasteringModuleInspector.h"

#include <algorithm>

namespace {
using Type=dozi::core::MasteringModuleType;
juce::String moduleName(Type type){switch(type){case Type::linearPhaseEq:return "Corrective EQ";case Type::dynamicEq:return "Dynamic EQ";case Type::deEsser:return "De-Esser";case Type::broadbandCompressor:return "Glue Compressor";case Type::multibandCompressor:return "Multiband Compressor";case Type::saturation:return "Saturation";case Type::stereoWidthMonoBass:return "Width / Mono Bass";case Type::truePeakLimiter:return "True Peak Limiter";}return "Module";}
bool supportsHardwareView(Type type){return type==Type::linearPhaseEq||type==Type::dynamicEq||type==Type::deEsser;}
struct Spec{double minimum,maximum,interval;juce::String suffix;};
Spec specFor(const std::string&key,double value){
    if(key.find("frequencyHz")!=std::string::npos||key.find("CrossoverHz")!=std::string::npos)return {20,20000,1," Hz"};
    if(key.find("threshold")!=std::string::npos)return {-60,0,.1," dBFS"};
    if(key.find("ceiling")!=std::string::npos)return {-6,0,.1," dBTP"};
    if(key.find("maximumCutDb")!=std::string::npos||key.find("maximumReductionDb")!=std::string::npos||key.find("maximumCompensationDb")!=std::string::npos)return {0,12,.1," dB"};
    if(key=="inputGainDb")return {-24,36,.1," dB"};
    if(key.find("GainDb")!=std::string::npos||key.find("gainDb")!=std::string::npos||key.find("TrimDb")!=std::string::npos)return {-12,12,.1," dB"};
    if(key.find("driveDb")!=std::string::npos)return {0,12,.1," dB"};
    if(key.find("attackMs")!=std::string::npos||key.find("releaseMs")!=std::string::npos||key.find("lookaheadMs")!=std::string::npos)return {.1,1000,.1," ms"};
    if(key.find("ratio")!=std::string::npos)return {1,20,.1," : 1"};
    if(key.find("width")!=std::string::npos||key=="mix")return {0,2,.01,{}};
    if(key=="q")return {.1,20,.1,{}};
    if(key=="mode"||key=="automaticLevelCompensation")return {0,1,1,{}};
    const auto span=std::max(10.0,std::abs(value)*2);return {-span,span,.01,{}};
}
juce::String displayName(std::string key){for(auto&c:key)if(c=='.')c=' ';juce::String text(key);return text.replace("frequencyHz","Frequency").replace("thresholdDbfs","Threshold").replace("inputGainDb","Input Gain").replace("ceilingDbtp","Ceiling").replace("lookaheadMs","Lookahead").replace("releaseMs","Release").replace("attackMs","Attack").replace("gainDb","Gain").replace("maximum","Maximum ").replace("monoBassCrossoverHz","Mono Bass Crossover").replace("automaticLevelCompensation","Automatic Level Compensation (0 Off, 1 On)").replace("mode","Mode (0 Tape, 1 Tube)");}
}

MasteringModuleInspector::MasteringModuleInspector(){addAndMakeVisible(moduleSelector);addAndMakeVisible(hardwareButton);addAndMakeVisible(technicalButton);addAndMakeVisible(enabledButton);addAndMakeVisible(viewport);addAndMakeVisible(hardwareCanvas);hardwareCanvas.addAndMakeVisible(correctiveEqHardware);hardwareCanvas.addAndMakeVisible(processorHardware);viewport.setViewedComponent(&parameterContent,false);viewport.setScrollBarsShown(true,false);for(auto*button:{&hardwareButton,&technicalButton}){button->setClickingTogglesState(true);button->setRadioGroupId(2001);}hardwareButton.onClick=[this]{showHardware(true);};technicalButton.onClick=[this]{showHardware(false);};moduleSelector.onChange=[this]{rebuildParameters();};enabledButton.onClick=[this]{if(!plan)return;const auto index=moduleSelector.getSelectedItemIndex();if(index<0||index>=static_cast<int>(plan->modules.size()))return;plan->modules[static_cast<std::size_t>(index)].bypassed=!enabledButton.getToggleState();if(onPlanChanged)onPlanChanged();};const auto hardwareChanged=[this]{if(plan){const auto index=moduleSelector.getSelectedItemIndex();if(index>=0&&index<static_cast<int>(plan->modules.size()))enabledButton.setToggleState(!plan->modules[static_cast<std::size_t>(index)].bypassed,juce::dontSendNotification);}if(onPlanChanged)onPlanChanged();};correctiveEqHardware.onModuleChanged=hardwareChanged;processorHardware.onModuleChanged=hardwareChanged;hardwareButton.setToggleState(true,juce::dontSendNotification);}
void MasteringModuleInspector::setPlan(dozi::core::MasteringPlan*value){plan=value;rebuildModules();}
void MasteringModuleInspector::setTelemetry(const std::vector<dozi::core::ProcessorTelemetry>&value){telemetry=value;processorHardware.setAvailableTelemetry(telemetry);}
void MasteringModuleInspector::updateTelemetry(const dozi::core::ProcessorTelemetry&value){const auto found=std::ranges::find(telemetry,value.type,&dozi::core::ProcessorTelemetry::type);if(found==telemetry.end())telemetry.push_back(value);else*found=value;processorHardware.setAvailableTelemetry(telemetry);}
void MasteringModuleInspector::rebuildModules(){const auto previous=moduleSelector.getSelectedItemIndex();moduleSelector.clear(juce::dontSendNotification);if(plan)for(std::size_t index=0;index<plan->modules.size();++index)moduleSelector.addItem(moduleName(plan->modules[index].type),static_cast<int>(index)+1);if(plan&&!plan->modules.empty())moduleSelector.setSelectedItemIndex(juce::jlimit(0,static_cast<int>(plan->modules.size())-1,std::max(0,previous)),juce::dontSendNotification);rebuildParameters();}
void MasteringModuleInspector::rebuildParameters(){controls.clear();parameterContent.removeAllChildren();if(!plan){enabledButton.setEnabled(false);hardwareButton.setEnabled(false);correctiveEqHardware.setModule(nullptr);processorHardware.setModule(nullptr);correctiveEqHardware.setVisible(false);processorHardware.setVisible(false);viewport.setVisible(true);enabledButton.setVisible(false);resized();return;}const auto index=moduleSelector.getSelectedItemIndex();if(index<0||index>=static_cast<int>(plan->modules.size()))return;auto&module=plan->modules[static_cast<std::size_t>(index)];const auto corrective=module.type==Type::linearPhaseEq;const auto supportsHardware=supportsHardwareView(module.type);hardwareButton.setEnabled(supportsHardware);correctiveEqHardware.setModule(corrective?&module:nullptr);processorHardware.setModule(supportsHardware&&!corrective?&module:nullptr);enabledButton.setEnabled(true);enabledButton.setToggleState(!module.bypassed,juce::dontSendNotification);for(const auto&[key,value]:module.parameters){ParameterControl control;control.key=key;control.label=std::make_unique<juce::Label>();control.slider=std::make_unique<juce::Slider>();control.label->setText(displayName(key),juce::dontSendNotification);const auto spec=specFor(key,value);control.slider->setRange(spec.minimum,spec.maximum,spec.interval);control.slider->setValue(value,juce::dontSendNotification);control.slider->setTextValueSuffix(spec.suffix);control.slider->setSliderStyle(juce::Slider::LinearHorizontal);control.slider->setTextBoxStyle(juce::Slider::TextBoxRight,false,100,24);auto*slider=control.slider.get();slider->onValueChange=[this,key,slider]{if(!plan)return;const auto selected=moduleSelector.getSelectedItemIndex();if(selected<0||selected>=static_cast<int>(plan->modules.size()))return;plan->modules[static_cast<std::size_t>(selected)].parameters[key]=slider->getValue();if(onPlanChanged)onPlanChanged();};parameterContent.addAndMakeVisible(*control.label);parameterContent.addAndMakeVisible(*control.slider);controls.push_back(std::move(control));}showHardware(hardwarePreferred&&supportsHardware,false);}
void MasteringModuleInspector::showHardware(bool visible,bool rememberPreference){if(rememberPreference)hardwarePreferred=visible;hardwareVisible=visible&&hardwareButton.isEnabled();hardwareButton.setToggleState(hardwareVisible,juce::dontSendNotification);technicalButton.setToggleState(!hardwareVisible,juce::dontSendNotification);enabledButton.setVisible(!hardwareVisible);hardwareCanvas.setVisible(hardwareVisible);const auto selected=moduleSelector.getSelectedItemIndex();const auto corrective=plan&&selected>=0&&plan->modules[static_cast<std::size_t>(selected)].type==Type::linearPhaseEq;if(plan&&selected>=0){auto&parameters=plan->modules[static_cast<std::size_t>(selected)].parameters;if(hardwareVisible){if(corrective)correctiveEqHardware.refreshFromModule();else processorHardware.refreshFromModule();}else for(auto&control:controls)if(control.slider&&parameters.contains(control.key))control.slider->setValue(parameters.at(control.key),juce::dontSendNotification);}correctiveEqHardware.setVisible(hardwareVisible&&corrective);processorHardware.setVisible(hardwareVisible&&!corrective);viewport.setVisible(!hardwareVisible);viewport.setViewPosition(0,0);resized();}
void MasteringModuleInspector::resized(){auto area=getLocalBounds();auto header=area.removeFromTop(34);moduleSelector.setBounds(header.removeFromLeft(260));header.removeFromLeft(8);hardwareButton.setBounds(header.removeFromLeft(110));header.removeFromLeft(5);technicalButton.setBounds(header.removeFromLeft(110));if(hardwareVisible){hardwareCanvas.setBounds(area.reduced(0,6));const auto corrective=plan&&moduleSelector.getSelectedItemIndex()>=0&&plan->modules[static_cast<std::size_t>(moduleSelector.getSelectedItemIndex())].type==Type::linearPhaseEq;const float designWidth=1200.0f,designHeight=corrective?577.0f:650.0f;const auto scale=juce::jmin(hardwareCanvas.getWidth()/designWidth,hardwareCanvas.getHeight()/designHeight);const auto offsetX=(hardwareCanvas.getWidth()-designWidth*scale)*0.5f,offsetY=(hardwareCanvas.getHeight()-designHeight*scale)*0.5f;auto&active=corrective?static_cast<juce::Component&>(correctiveEqHardware):static_cast<juce::Component&>(processorHardware);active.setBounds(0,0,static_cast<int>(designWidth),static_cast<int>(designHeight));active.setTransform(juce::AffineTransform(scale,0.0f,offsetX,0.0f,scale,offsetY));return;}correctiveEqHardware.setTransform({});processorHardware.setTransform({});enabledButton.setBounds(area.removeFromTop(30));viewport.setBounds(area);parameterContent.setSize(juce::jmax(100,area.getWidth()-12),static_cast<int>(controls.size())*52);int y=0;for(auto&control:controls){control.label->setBounds(4,y,parameterContent.getWidth()-8,18);control.slider->setBounds(4,y+18,parameterContent.getWidth()-8,30);y+=52;}}
