#include "MasteringHardwareControls.h"
#include "MasteringModuleInspector.h"

#include <cmath>
#include <iostream>
#include <map>
#include <ranges>
#include <string>
#include <vector>

namespace {
using Type=dozi::core::MasteringModuleType;
int failures=0;
void expect(bool condition,const std::string&message){if(!condition){std::cerr<<"FAIL: "<<message<<'\n';++failures;}}
template<class T>T* child(juce::Component&parent,const std::string&id){return dynamic_cast<T*>(parent.findChildWithID(juce::String(id)));}
template<class T>void descendants(juce::Component&parent,std::vector<T*>&found){for(auto*component:parent.getChildren()){if(auto*value=dynamic_cast<T*>(component))found.push_back(value);descendants(*component,found);}}
dozi::core::MasteringModulePlan module(Type type,std::map<std::string,double>parameters){dozi::core::MasteringModulePlan value;value.type=type;value.parameters=std::move(parameters);value.recommendedParameters=value.parameters;value.styleParameters=value.parameters;if(!value.parameters.empty()){if(type==Type::saturation&&value.parameters.contains("automaticLevelCompensation")){value.recommendedParameters["automaticLevelCompensation"]=0;value.styleParameters["automaticLevelCompensation"]=1;}else if(type==Type::stereoWidthMonoBass&&value.parameters.contains("balance")){value.recommendedParameters["balance"]=.1;value.styleParameters["balance"]=.2;}else if(type==Type::truePeakLimiter&&value.parameters.contains("ceilingDbtp")){value.recommendedParameters["ceilingDbtp"]=-2;value.styleParameters["ceilingDbtp"]=-3;}else{value.recommendedParameters.begin()->second+=1;value.styleParameters.begin()->second+=2;}}return value;}
void setSlider(SkinnedProcessorHardwarePanel&panel,dozi::core::MasteringModulePlan&module,const std::string&key){auto*slider=child<juce::Slider>(panel,key);expect(slider!=nullptr&&slider->isVisible(),key+" has a visible hardware knob");if(!slider)return;const auto old=module.parameters.at(key);auto next=old+slider->getInterval();if(next>slider->getMaximum())next=old-slider->getInterval();slider->setValue(next,juce::sendNotificationSync);expect(std::abs(module.parameters.at(key)-next)<1e-9,key+" knob writes its parameter");}
void toggle(SkinnedProcessorHardwarePanel&panel,dozi::core::MasteringModulePlan&module,const std::string&key){auto*button=child<juce::TextButton>(panel,key);expect(button!=nullptr&&button->isVisible(),key+" has a visible hardware switch");if(!button)return;const auto old=module.parameters.at(key);button->setToggleState(old<.5,juce::dontSendNotification);button->onClick();expect(module.parameters.at(key)!=(old>.5?1.0:0.0),key+" switch writes its parameter");}
void shared(SkinnedProcessorHardwarePanel&panel,dozi::core::MasteringModulePlan&module,const std::string&name){auto*in=child<juce::TextButton>(panel,"in");auto*automatic=child<juce::TextButton>(panel,"auto");auto*reset=child<juce::TextButton>(panel,"reset");expect(in&&automatic&&reset,name+" exposes IN, AUTO, and RESET");if(!in||!automatic||!reset)return;const auto bypassed=module.bypassed;in->setToggleState(bypassed,juce::dontSendNotification);in->onClick();expect(module.bypassed!=bypassed,name+" IN toggles bypass");module.parameters.begin()->second+=3;automatic->onClick();expect(module.parameters==module.recommendedParameters,name+" AUTO restores analysis recommendation");module.parameters.begin()->second+=3;reset->onClick();expect(module.parameters==module.styleParameters,name+" RESET restores selected style independently of AUTO");expect(module.recommendedParameters!=module.styleParameters,name+" AUTO and RESET snapshots are distinct");}
juce::uint64 imageHash(SkinnedProcessorHardwarePanel&panel){juce::Image image(juce::Image::ARGB,1200,650,true);juce::Graphics graphics(image);panel.paintEntireComponent(graphics,true);juce::Image::BitmapData data(image,juce::Image::BitmapData::readOnly);juce::uint64 hash=1469598103934665603ULL;for(int y=0;y<data.height;++y)for(int x=0;x<data.width;++x){hash^=data.getPixelColour(x,y).getARGB();hash*=1099511628211ULL;}return hash;}
void displayChanges(SkinnedProcessorHardwarePanel&panel,dozi::core::MasteringModulePlan&module,const std::string&key,const std::string&name){const auto before=imageHash(panel);auto*slider=child<juce::Slider>(panel,key);expect(slider!=nullptr,name+" display driver exists");if(!slider)return;auto next=slider->getValue()+std::max(slider->getInterval(),1.0);if(next>slider->getMaximum())next=slider->getValue()-std::max(slider->getInterval(),1.0);slider->setValue(next,juce::sendNotificationSync);panel.repaint();const auto after=imageHash(panel);expect(before!=after,name+" rendered display changes with "+key);expect(std::abs(module.parameters.at(key)-next)<1e-9,name+" display uses current module state");}
}

int main(){
    juce::ScopedJuceInitialiser_GUI initialise;
    {
        CorrectiveEqHardwarePanel eq;eq.setSize(1200,577);auto value=module(Type::linearPhaseEq,{{"band1.frequencyHz",80},{"band1.gainDb",-3},{"band1.q",1},{"band2.frequencyHz",400},{"band2.gainDb",-2},{"band2.q",1.5},{"band3.frequencyHz",2800},{"band3.gainDb",-4},{"band3.q",2},{"band4.frequencyHz",10000},{"band4.gainDb",-1},{"band4.q",.8}});value.recommendedParameters=value.parameters;value.styleParameters=value.parameters;value.recommendedParameters["band1.gainDb"]=-2;value.styleParameters["band1.gainDb"]=-1;eq.setModule(&value);
        auto*in=child<juce::TextButton>(eq,"in");auto*automatic=child<juce::TextButton>(eq,"auto");auto*reset=child<juce::TextButton>(eq,"reset");auto*bandIn=child<juce::TextButton>(eq,"bandIn");auto*resetBand=child<juce::TextButton>(eq,"resetBand");expect(in&&automatic&&reset&&bandIn&&resetBand,"Corrective EQ exposes IN, AUTO, RESET, BAND IN, and RESET BAND");if(in){in->setToggleState(false,juce::dontSendNotification);in->onClick();expect(value.bypassed,"Corrective EQ IN toggles bypass");}for(int index=0;index<4;++index){auto*gain=child<juce::Slider>(eq,"bandGain"+std::to_string(index));expect(gain&&gain->isVisible(),"Corrective EQ band gain "+std::to_string(index)+" is visible");if(gain){const auto old=gain->getValue();gain->setValue(old+.25,juce::sendNotificationSync);expect(gain->getValue()!=old,"Corrective EQ band gain responds");}}
        auto*selectedGain=child<juce::Slider>(eq,"bandGain2");if(selectedGain)selectedGain->setValue(selectedGain->getValue()-.1,juce::sendNotificationSync);auto*frequency=child<juce::Slider>(eq,"detail0");auto*gain=child<juce::Slider>(eq,"detail1");auto*q=child<juce::Slider>(eq,"detail2");expect(frequency&&gain&&q,"Corrective EQ selected-band detail controls exist");if(frequency&&gain&&q){frequency->setValue(3000,juce::sendNotificationSync);gain->setValue(-2.5,juce::sendNotificationSync);q->setValue(3,juce::sendNotificationSync);expect(std::abs(value.parameters["band3.frequencyHz"]-3000)<1e-9&&std::abs(value.parameters["band3.gainDb"]+2.5)<1e-9&&std::abs(value.parameters["band3.q"]-3)<1e-9,"Corrective EQ detail controls write selected band");}
        if(bandIn){bandIn->setToggleState(false,juce::dontSendNotification);bandIn->onClick();expect(std::abs(value.parameters["band3.gainDb"])<1e-9,"Corrective EQ BAND IN disables selected band");bandIn->setToggleState(true,juce::dontSendNotification);bandIn->onClick();expect(value.parameters["band3.gainDb"]<0,"Corrective EQ BAND IN restores selected band");}if(resetBand){value.parameters["band3.q"]=9;resetBand->onClick();expect(std::abs(value.parameters["band3.q"]-2)<1e-9,"Corrective EQ RESET BAND restores captured band settings");}if(automatic){value.parameters["band1.gainDb"]=-.25;automatic->onClick();expect(std::abs(value.parameters["band1.gainDb"]+2)<1e-9,"Corrective EQ AUTO restores analysis recommendation");}if(reset){reset->onClick();expect(std::abs(value.parameters["band1.gainDb"]+1)<1e-9,"Corrective EQ RESET restores selected style independently of AUTO");}
    }
    SkinnedProcessorHardwarePanel panel;panel.setSize(1200,650);
    {
        auto value=module(Type::dynamicEq,{{"band1.frequencyHz",80},{"band1.q",1},{"band1.gainDb",-4},{"band1.thresholdDbfs",-26},{"band1.attackMs",10},{"band1.releaseMs",120},{"band1.enabled",1},{"band1.listen",0}});panel.setModule(&value);shared(panel,value,"Dynamic EQ");for(const auto*key:{"band1.frequencyHz","band1.thresholdDbfs","band1.gainDb"})setSlider(panel,value,key);toggle(panel,value,"band1.enabled");auto*listen=child<juce::TextButton>(panel,"globalListen");expect(listen&&listen->isVisible(),"Dynamic EQ exposes global Listen");if(listen){listen->setToggleState(true,juce::dontSendNotification);listen->onClick();expect(value.parameters["band1.listen"]==1,"Dynamic EQ global Listen writes band Listen");}displayChanges(panel,value,"band1.gainDb","Dynamic EQ");
    }
    {
        auto value=module(Type::deEsser,{{"frequencyHz",6500},{"q",1},{"thresholdDbfs",-30},{"ratio",3},{"maximumReductionDb",6},{"attackMs",2},{"releaseMs",80},{"listen",0}});panel.setModule(&value);shared(panel,value,"De-Esser");for(const auto*key:{"frequencyHz","thresholdDbfs","maximumReductionDb","releaseMs"})setSlider(panel,value,key);toggle(panel,value,"listen");displayChanges(panel,value,"frequencyHz","De-Esser");
    }
    {
        auto value=module(Type::broadbandCompressor,{{"thresholdDbfs",-18},{"attackMs",30},{"releaseMs",150},{"ratio",2},{"makeupGainDb",0},{"sidechainHpfHz",80},{"automaticRelease",0}});panel.setModule(&value);shared(panel,value,"Glue compressor");for(const auto*key:{"thresholdDbfs","attackMs","releaseMs","ratio","makeupGainDb","sidechainHpfHz"})setSlider(panel,value,key);toggle(panel,value,"automaticRelease");displayChanges(panel,value,"thresholdDbfs","Glue compressor");
    }
    {
        auto value=module(Type::multibandCompressor,{{"lowCrossoverHz",120},{"midCrossoverHz",700},{"highCrossoverHz",4000},{"ratio",2},{"maximumGainReductionDb",3},{"low.thresholdDbfs",-18},{"low.maximumReductionDb",3},{"low.solo",0},{"lowMid.thresholdDbfs",-18},{"lowMid.maximumReductionDb",3},{"lowMid.solo",0},{"highMid.thresholdDbfs",-18},{"highMid.maximumReductionDb",3},{"highMid.solo",0},{"high.thresholdDbfs",-18},{"high.maximumReductionDb",3},{"high.solo",0}});panel.setModule(&value);shared(panel,value,"Multiband compressor");for(const auto*band:{"low","lowMid","highMid","high"}){setSlider(panel,value,std::string(band)+".thresholdDbfs");setSlider(panel,value,std::string(band)+".maximumReductionDb");toggle(panel,value,std::string(band)+".solo");}for(const auto*key:{"lowCrossoverHz","midCrossoverHz","highCrossoverHz"})setSlider(panel,value,key);displayChanges(panel,value,"midCrossoverHz","Multiband compressor");
    }
    {
        auto value=module(Type::saturation,{{"driveDb",3},{"character",1},{"mix",.8},{"outputTrimDb",0},{"oversamplingFactor",4},{"automaticLevelCompensation",1},{"maximumCompensationDb",3},{"outputCeilingDbfs",-.1}});panel.setModule(&value);shared(panel,value,"Saturation");for(const auto*key:{"driveDb","character","mix","outputTrimDb"})setSlider(panel,value,key);for(int index=0;index<3;++index){auto*button=child<juce::TextButton>(panel,"character"+std::to_string(index));expect(button&&button->isVisible(),"Saturation character button "+std::to_string(index)+" is visible");if(button){button->onClick();expect(value.parameters["character"]==index,"Saturation character button writes mode");}}auto*hq=child<juce::TextButton>(panel,"hq");expect(hq&&hq->isVisible(),"Saturation exposes HQ");if(hq){hq->setToggleState(true,juce::dontSendNotification);hq->onClick();expect(value.parameters["oversamplingFactor"]==8,"Saturation HQ enables 8x oversampling");}displayChanges(panel,value,"driveDb","Saturation");
    }
    {
        auto value=module(Type::stereoWidthMonoBass,{{"monoBassCrossoverHz",120},{"sideTrimDb",0},{"widthFactor",1},{"balance",0},{"monoCheck",0},{"swapLeftRight",0}});panel.setModule(&value);shared(panel,value,"Width / Mono Bass");for(const auto*key:{"monoBassCrossoverHz","sideTrimDb","widthFactor","balance"})setSlider(panel,value,key);for(const auto*key:{"monoCheck","swapLeftRight"})toggle(panel,value,key);displayChanges(panel,value,"widthFactor","Width / Mono Bass");
    }
    {
        auto value=module(Type::truePeakLimiter,{{"inputGainDb",3},{"ceilingDbtp",-1},{"releaseMs",100},{"lookaheadMs",5},{"linked",1},{"truePeakEnabled",1}});panel.setModule(&value);shared(panel,value,"True-peak limiter");for(const auto*key:{"inputGainDb","ceilingDbtp","releaseMs","lookaheadMs"})setSlider(panel,value,key);for(const auto*key:{"linked","truePeakEnabled"})toggle(panel,value,key);displayChanges(panel,value,"ceilingDbtp","True-peak limiter");
    }
    {
        const auto verifyTelemetry=[&](Type type,std::map<std::string,double>parameters,const std::string&name){auto value=module(type,std::move(parameters));panel.setModule(&value);panel.setTelemetry({});const auto before=imageHash(panel);dozi::core::ProcessorTelemetry measured;measured.type=type;measured.inputPeakDbfs=-3;measured.outputPeakDbfs=-6;measured.maximumGainReductionDb=3.5;measured.phaseCorrelation=.42;measured.peakEventCount=7;for(std::size_t index=0;index<measured.spectrumDbfs.size();++index)measured.spectrumDbfs[index]=-60+static_cast<double>(index);measured.vectorscope={{{.8,-.2}},{{.3,.6}},{{-.4,.2}}};panel.setTelemetry(measured);const auto after=imageHash(panel);expect(before!=after,name+" display renders measured DSP telemetry");};
        verifyTelemetry(Type::dynamicEq,{{"band1.frequencyHz",1000},{"band1.gainDb",-4},{"band1.q",1},{"band1.thresholdDbfs",-30}},"Spectrum");verifyTelemetry(Type::broadbandCompressor,{{"thresholdDbfs",-18},{"ratio",2},{"attackMs",30},{"releaseMs",100},{"makeupGainDb",0}},"Reduction meter");verifyTelemetry(Type::stereoWidthMonoBass,{{"widthFactor",1},{"monoBassCrossoverHz",120}},"Vectorscope");verifyTelemetry(Type::truePeakLimiter,{{"inputGainDb",3},{"ceilingDbtp",-1},{"releaseMs",100},{"lookaheadMs",5}},"Peak-event meter");
    }
    {
        dozi::core::MasteringPlan plan;plan.modules.push_back(module(Type::dynamicEq,{{"band1.frequencyHz",1000},{"band1.q",1},{"band1.gainDb",-3.3},{"band1.thresholdDbfs",-26},{"band1.attackMs",10},{"band1.releaseMs",120},{"band1.enabled",1},{"band1.listen",0}}));MasteringModuleInspector inspector;inspector.setSize(1200,700);inspector.setPlan(&plan);std::vector<SkinnedProcessorHardwarePanel*>hardwarePanels;descendants(inspector,hardwarePanels);expect(!hardwarePanels.empty(),"Inspector contains processor hardware panel");if(!hardwarePanels.empty()){auto*gain=child<juce::Slider>(*hardwarePanels.front(),"band1.gainDb");expect(gain!=nullptr,"Inspector Hardware view exposes Dynamic EQ gain");if(gain)gain->setValue(-4.4,juce::sendNotificationSync);}std::vector<juce::TextButton*>buttons;descendants(inspector,buttons);auto technical=std::ranges::find_if(buttons,[](auto*button){return button->getButtonText()=="Technical";});auto hardware=std::ranges::find_if(buttons,[](auto*button){return button->getButtonText()=="Hardware";});expect(technical!=buttons.end()&&hardware!=buttons.end(),"Inspector exposes Hardware and Technical selectors");if(technical!=buttons.end())(*technical)->onClick();std::vector<juce::Slider*>sliders;descendants(inspector,sliders);const auto technicalGain=std::ranges::find_if(sliders,[](auto*slider){return std::abs(slider->getValue()+4.4)<1e-9&&slider->getSliderStyle()==juce::Slider::LinearHorizontal;});expect(technicalGain!=sliders.end(),"Hardware change refreshes Technical control");if(technicalGain!=sliders.end())(*technicalGain)->setValue(-5.5,juce::sendNotificationSync);if(hardware!=buttons.end())(*hardware)->onClick();if(!hardwarePanels.empty()){auto*gain=child<juce::Slider>(*hardwarePanels.front(),"band1.gainDb");expect(gain&&std::abs(gain->getValue()+5.5)<1e-9,"Technical change refreshes Hardware control");}
    }
    {
        for(const auto type:{Type::broadbandCompressor,Type::multibandCompressor,Type::saturation,Type::stereoWidthMonoBass,Type::truePeakLimiter}){dozi::core::MasteringPlan plan;plan.modules.push_back(module(type,{{"thresholdDbfs",-18},{"ratio",2}}));MasteringModuleInspector inspector;inspector.setSize(1200,700);inspector.setPlan(&plan);std::vector<juce::TextButton*>buttons;descendants(inspector,buttons);const auto hardware=std::ranges::find_if(buttons,[](auto*button){return button->getButtonText()=="Hardware";});const auto technical=std::ranges::find_if(buttons,[](auto*button){return button->getButtonText()=="Technical";});expect(hardware!=buttons.end()&&!(*hardware)->isEnabled(),"Removed processor Hardware view stays unavailable");expect(technical!=buttons.end()&&(*technical)->getToggleState(),"Removed processor opens in Technical view");std::vector<SkinnedProcessorHardwarePanel*>hardwarePanels;descendants(inspector,hardwarePanels);expect(!hardwarePanels.empty()&&!hardwarePanels.front()->isVisible(),"Removed processor hardware panel stays hidden");std::vector<juce::Slider*>sliders;descendants(inspector,sliders);expect(std::ranges::any_of(sliders,[](auto*slider){return slider->isVisible()&&slider->getSliderStyle()==juce::Slider::LinearHorizontal;}),"Removed processor retains Technical controls");}
    }
    if(failures==0)std::cout<<"All hardware control binding tests passed\n";
    return failures==0?0:1;
}
