#include "dozi/core/MasteringDsp.h"

#include <algorithm>
#include <cmath>
#include <iostream>
#include <numbers>
#include <stdexcept>
#include <string>
#include <type_traits>

namespace {
using namespace dozi::core;
constexpr int rate=48000;
int failures=0;
void expect(bool condition,const std::string& message){if(!condition){std::cerr<<"FAIL: "<<message<<'\n';++failures;}}
StereoAudioBuffer tone(double frequency,double amplitude=.7,double seconds=.3,double rightScale=1){StereoAudioBuffer a;a.sampleRate=rate;const auto frames=static_cast<std::size_t>(rate*seconds);a.left.resize(frames);a.right.resize(frames);for(std::size_t i=0;i<frames;++i){const auto v=amplitude*std::sin(2*std::numbers::pi*frequency*static_cast<double>(i)/rate);a.left[i]=v;a.right[i]=v*rightScale;}return a;}
StereoAudioBuffer transient(){auto a=tone(1000,.08,.35);for(std::size_t i=rate/20;i<rate/20+1500;++i)a.left[i]=a.right[i]=.95*std::sin(2*std::numbers::pi*1000*static_cast<double>(i)/rate);return a;}
double difference(const StereoAudioBuffer&a,const StereoAudioBuffer&b){double total=0;for(std::size_t i=0;i<a.left.size();++i)total+=std::abs(a.left[i]-b.left[i])+std::abs(a.right[i]-b.right[i]);return total;}
double power(const StereoAudioBuffer&a){double total=0;for(std::size_t i=0;i<a.left.size();++i)total+=a.left[i]*a.left[i]+a.right[i]*a.right[i];return total/std::max<std::size_t>(1,a.left.size()*2);}
double peak(const StereoAudioBuffer&a){double p=0;for(std::size_t i=0;i<a.left.size();++i)p=std::max({p,std::abs(a.left[i]),std::abs(a.right[i])});return p;}
template<class Processor,class Settings>void expectBypass(const std::string&name,const Processor&processor,Settings settings){auto input=tone(997);const auto original=input;settings.bypassed=true;if constexpr(std::is_void_v<decltype(processor.process(input,settings))>)processor.process(input,settings);else(void)processor.process(input,settings);expect(difference(input,original)<1e-12,name+" bypass is transparent");}
}

int main(){
    {
        LinearPhaseEq processor;LinearPhaseEqSettings base{false,{{1000,-6,1}},257};expectBypass("Corrective EQ",processor,base);
        auto input=tone(1000),deep=input,shallow=input,narrow=input;processor.process(deep,base);auto less=base;less.bands[0].gainDb=-2;processor.process(shallow,less);auto q=base;q.bands[0].q=8;processor.process(narrow,q);
        expect(power(deep)<power(shallow),"Corrective EQ gain controls cut depth");expect(difference(deep,narrow)>1e-3,"Corrective EQ Q changes bandwidth");auto offTarget=tone(5000);const auto offOriginal=offTarget;processor.process(offTarget,base);expect(difference(deep,input)>difference(offTarget,offOriginal),"Corrective EQ frequency targets the selected band");
    }
    {
        DynamicEqualizer processor;DynamicEqSettings base{false,{{1000,1,-36,8,2,100,true,false}}};expectBypass("Dynamic EQ",processor,base);
        auto input=tone(1000),active=input,disabled=input,highThreshold=input,smallRange=input,differentQ=input,differentTiming=input,listen=input;processor.process(active,base);auto s=base;s.bands[0].enabled=false;processor.process(disabled,s);expect(difference(disabled,input)<1e-12,"Dynamic EQ band enable disables processing");s=base;s.bands[0].thresholdDbfs=-1;processor.process(highThreshold,s);expect(difference(active,input)>difference(highThreshold,input),"Dynamic EQ threshold controls detection");s=base;s.bands[0].maximumCutDb=1;processor.process(smallRange,s);expect(power(active)<power(smallRange),"Dynamic EQ range limits reduction");s=base;s.bands[0].q=8;processor.process(differentQ,s);expect(difference(active,differentQ)>1e-3,"Dynamic EQ Q changes response");s=base;s.bands[0].attackMs=80;s.bands[0].releaseMs=600;processor.process(differentTiming,s);expect(difference(active,differentTiming)>1e-3,"Dynamic EQ attack and release change envelope timing");s=base;s.bands[0].listen=true;processor.process(listen,s);expect(difference(listen,active)>1e-3&&power(listen)<power(input),"Dynamic EQ Listen outputs detected material");auto other=tone(6000);const auto otherOriginal=other;processor.process(other,base);expect(difference(active,input)>difference(other,otherOriginal),"Dynamic EQ frequency targets its band");
    }
    {
        DeEsser processor;DeEsserSettings base{false,6500,2,-36,6,8,1,100,false};expectBypass("De-Esser",processor,base);
        auto input=tone(6500),active=input,threshold=input,range=input,q=input,ratio=input,timing=input,listen=input;processor.process(active,base);auto s=base;s.thresholdDbfs=-1;processor.process(threshold,s);expect(difference(active,input)>difference(threshold,input),"De-Esser threshold controls detection");s=base;s.maximumReductionDb=1;processor.process(range,s);expect(power(active)<power(range),"De-Esser range limits reduction");s=base;s.q=8;processor.process(q,s);expect(difference(active,q)>1e-3,"De-Esser Q changes bandwidth");s=base;s.ratio=1;processor.process(ratio,s);expect(difference(ratio,input)<1e-9,"De-Esser ratio 1:1 produces no reduction");s=base;s.attackMs=40;s.releaseMs=600;processor.process(timing,s);expect(difference(active,timing)>1e-3,"De-Esser attack and release change timing");s=base;s.listen=true;processor.process(listen,s);expect(difference(listen,active)>1e-3,"De-Esser Listen outputs removed sibilance");auto low=tone(500);const auto lowOriginal=low;processor.process(low,base);expect(difference(active,input)>difference(low,lowOriginal),"De-Esser frequency selects sibilance band");
    }
    {
        BroadbandCompressor processor;CompressorSettings base{false,-30,4,2,120,0,0,false};expectBypass("Glue compressor",processor,base);
        auto input=transient(),active=input,threshold=input,ratio=input,attack=input,release=input,makeup=input,automatic=input;processor.process(active,base);auto s=base;s.thresholdDbfs=-3;processor.process(threshold,s);expect(power(active)<power(threshold),"Compressor threshold changes compression");s=base;s.ratio=1;processor.process(ratio,s);expect(difference(ratio,input)<1e-9,"Compressor ratio 1:1 produces no compression");s=base;s.attackMs=80;processor.process(attack,s);expect(difference(active,attack)>1e-3,"Compressor attack changes transient response");s=base;s.releaseMs=800;processor.process(release,s);expect(difference(active,release)>1e-3,"Compressor release changes recovery");s=base;s.makeupGainDb=6;processor.process(makeup,s);expect(power(makeup)>power(active),"Compressor makeup gain changes output level");s=base;s.automaticRelease=true;processor.process(automatic,s);expect(difference(active,automatic)>1e-6,"Compressor automatic release changes recovery");auto bass=tone(40);auto noHpf=bass,withHpf=bass;s=base;processor.process(noHpf,s);s.sidechainHpfHz=120;processor.process(withHpf,s);expect(power(withHpf)>power(noHpf),"Compressor sidechain HPF reduces bass-triggered compression");
    }
    {
        MultibandCompressor processor;MultibandCompressorSettings base;base.lowCrossoverHz=120;base.midCrossoverHz=700;base.highCrossoverHz=4000;for(auto*s:{&base.low,&base.lowMid,&base.highMid,&base.high})*s={-36,4,2,120,8,false};expectBypass("Multiband compressor",processor,base);
        auto input=tone(1000),active=input,threshold=input,range=input,ratio=input,timing=input,solo=input,crossovers=input;processor.process(active,base);auto s=base;s.highMid.thresholdDbfs=-1;processor.process(threshold,s);expect(difference(active,threshold)>1e-3,"Multiband per-band threshold changes processing");s=base;s.highMid.maximumReductionDb=1;processor.process(range,s);expect(difference(active,range)>1e-3,"Multiband per-band range limits reduction");s=base;s.highMid.ratio=1;processor.process(ratio,s);expect(difference(active,ratio)>1e-3,"Multiband per-band ratio changes processing");s=base;s.highMid.attackMs=80;s.highMid.releaseMs=600;processor.process(timing,s);expect(difference(active,timing)>1e-3,"Multiband attack and release change timing");s=base;s.highMid.solo=true;processor.process(solo,s);expect(difference(active,solo)>1e-3,"Multiband Solo isolates a band");s=base;s.lowCrossoverHz=200;s.midCrossoverHz=1200;s.highCrossoverHz=6000;processor.process(crossovers,s);expect(difference(active,crossovers)>1e-3,"Multiband crossover controls change band routing");bool threw=false;try{s=base;s.midCrossoverHz=80;processor.process(input,s);}catch(const std::invalid_argument&){threw=true;}expect(threw,"Multiband rejects unordered crossovers");
    }
    {
        HarmonicSaturator processor;SaturationSettings base{false,SaturationMode::warm,6,1,0,4,false,3,-.1};expectBypass("Saturation",processor,base);
        auto input=tone(997,.55),active=input,drive=input,dry=input,trim=input,clean=input,rich=input,hq=input,compensated=input,limited=input;processor.process(active,base);auto s=base;s.driveDb=0;processor.process(drive,s);expect(difference(active,drive)>1e-3,"Saturation drive changes harmonic shaping");s=base;s.mix=0;processor.process(dry,s);expect(difference(dry,input)<1e-9,"Saturation mix zero is dry");s=base;s.outputTrimDb=-6;processor.process(trim,s);expect(power(trim)<power(active),"Saturation output trim changes level");s=base;s.mode=SaturationMode::clean;processor.process(clean,s);s.mode=SaturationMode::rich;processor.process(rich,s);expect(difference(clean,rich)>1e-3,"Saturation Clean, Warm, and Rich are distinct");s=base;s.oversamplingFactor=8;processor.process(hq,s);expect(difference(active,hq)>1e-3,"Saturation HQ oversampling changes processing");s=base;s.automaticLevelCompensation=true;s.maximumCompensationDb=1;processor.process(compensated,s);expect(difference(active,compensated)>1e-3,"Saturation automatic level compensation changes gain within its limit");s=base;s.outputCeilingDbfs=-12;processor.process(limited,s);expect(peak(limited)<=std::pow(10.0,-12.0/20.0)+1e-9,"Saturation output ceiling is enforced");
    }
    {
        MasteringStereoProcessor processor;StereoProcessorSettings base{false,1.0,120,0,0,false,false};expectBypass("Width / Mono Bass",processor,base);
        auto input=tone(1000,.6,.3,-.4),width=input,crossover=input,trim=input,balance=input,mono=input,swapped=input;processor.process(width,base);auto s=base;s.widthFactor=.3;processor.process(crossover,s);expect(difference(width,crossover)>1e-3,"Stereo width changes side level");s=base;s.sideTrimDb=-6;processor.process(trim,s);expect(difference(width,trim)>1e-3,"Stereo side trim changes side level");s=base;s.balance=.75;processor.process(balance,s);expect(power(balance)<power(width),"Stereo balance attenuates one channel");s=base;s.monoCheck=true;processor.process(mono,s);expect(std::equal(mono.left.begin(),mono.left.end(),mono.right.begin(),[](double l,double r){return std::abs(l-r)<1e-12;}),"Mono Check produces identical channels");s=base;s.swapLeftRight=true;processor.process(swapped,s);expect(difference(width,swapped)>1e-3,"Swap L/R exchanges channels");auto bass=tone(50,.6,.3,-1),lowCross=bass,highCross=bass;s=base;s.monoBassCrossoverHz=30;processor.process(lowCross,s);s.monoBassCrossoverHz=300;processor.process(highCross,s);expect(difference(lowCross,highCross)>1e-3,"Mono-bass crossover changes low-frequency side removal");
    }
    {
        TruePeakLimiter processor;LimiterSettings base{false,6,-1,5,100,true,true};expectBypass("True-peak limiter",processor,base);
        auto input=tone(997,.9),active=input,lowerInput=input,ceiling=input,lookahead=input,release=input,unlinked=tone(997,.9,.3,.15),samplePeak=input;unlinked.left[0]=1.5;unlinked.right[0]=.1;const auto metrics=processor.process(active,base);auto s=base;s.inputGainDb=0;(void)processor.process(lowerInput,s);expect(difference(active,lowerInput)>1e-3,"Limiter input gain changes drive into limiting");s=base;s.ceilingDbtp=-6;(void)processor.process(ceiling,s);expect(peak(ceiling)<peak(active),"Limiter ceiling changes maximum output");s=base;s.lookaheadMs=.5;(void)processor.process(lookahead,s);expect(difference(active,lookahead)>1e-3,"Limiter lookahead changes gain trajectory");s=base;s.releaseMs=1000;(void)processor.process(release,s);expect(difference(active,release)>1e-3,"Limiter release changes recovery");s=base;s.linked=false;s.inputGainDb=0;(void)processor.process(unlinked,s);expect(std::abs(unlinked.right[0]-.1)<.05,"Limiter unlinked mode preserves the quieter channel");s=base;s.truePeakEnabled=false;(void)processor.process(samplePeak,s);expect(difference(active,samplePeak)>1e-6,"Limiter true-peak switch selects a different safety measurement");expect(metrics.maximumGainReductionDb>0,"Limiter reports gain reduction");expect(processor.truePeakDbtp(active)<=base.ceilingDbtp+.05,"Limiter respects true-peak ceiling");
    }
    if(failures==0)std::cout<<"All processor control DSP tests passed\n";
    return failures==0?0:1;
}
