#include "dozi/core/MasteringRenderer.h"
#include <sndfile.h>
#include <algorithm>
#include <cmath>
#include <filesystem>
#include <iostream>
#include <numbers>
#include <string>
#include <vector>
namespace { using namespace dozi::core;int failures=0;void expect(bool condition,const std::string&message){if(!condition){std::cerr<<"FAIL: "<<message<<'\n';++failures;}}std::filesystem::path temporary(const std::string&name){return std::filesystem::temp_directory_path()/("dozi-"+name+".wav");}void writeSource(const std::filesystem::path&path){SF_INFO info{};info.samplerate=48000;info.channels=2;info.format=SF_FORMAT_WAV|SF_FORMAT_FLOAT;auto*file=sf_open(path.c_str(),SFM_WRITE,&info);if(!file)throw std::runtime_error("Could not create renderer test source");std::vector<double>samples(48000*2);for(std::size_t i=0;i<48000;++i){const auto time=static_cast<double>(i)/48000;samples[2*i]=.72*std::sin(2*std::numbers::pi*1000*time)+.12*std::sin(2*std::numbers::pi*7000*time);samples[2*i+1]=.28*std::sin(2*std::numbers::pi*350*time)-.18*std::sin(2*std::numbers::pi*7000*time);}samples[200]=1.1;samples[201]=-.9;if(sf_writef_double(file,samples.data(),48000)!=48000){sf_close(file);throw std::runtime_error("Could not write renderer test source");}sf_close(file);}std::vector<double>read(const std::filesystem::path&path){SF_INFO info{};auto*file=sf_open(path.c_str(),SFM_READ,&info);if(!file)throw std::runtime_error("Could not read renderer test output");std::vector<double>samples(static_cast<std::size_t>(info.frames*info.channels));sf_readf_double(file,samples.data(),info.frames);sf_close(file);return samples;}double difference(const std::vector<double>&a,const std::vector<double>&b){double result=0;for(std::size_t i=0;i<std::min(a.size(),b.size());++i)result+=std::abs(a[i]-b[i]);return result;}MasteringPlan planWith(MasteringModulePlan module){MasteringPlan plan;plan.targetIntegratedLufs=-14;plan.truePeakCeilingDbtp=-1;plan.modules.push_back(std::move(module));return plan;}MasteringModulePlan module(MasteringModuleType type,std::map<std::string,double>parameters){MasteringModulePlan result;result.type=type;result.parameters=std::move(parameters);return result;} }
int main(){const auto source=temporary("audition-source");writeSource(source);MasteringRenderer renderer;
 {auto plan=planWith(module(MasteringModuleType::dynamicEq,{{"band1.frequencyHz",1000},{"band1.q",1},{"band1.gainDb",-8},{"band1.thresholdDbfs",-50},{"band1.attackMs",1},{"band1.releaseMs",100},{"band1.enabled",1},{"band1.listen",1}}));const auto audition=temporary("dynamic-listen"),exported=temporary("dynamic-export"),exportOff=temporary("dynamic-export-off");int callbackCount=0;const auto result=renderer.render(source,audition,plan,{},true,[&callbackCount](const ProcessorTelemetry&){++callbackCount;});(void)renderer.render(source,exported,plan,{},false);plan.modules[0].parameters["band1.listen"]=0;(void)renderer.render(source,exportOff,plan,{},false);expect(difference(read(audition),read(exported))>1,"Dynamic EQ Listen changes audition output");expect(difference(read(exported),read(exportOff))<1e-6,"Dynamic EQ Listen is excluded from export");expect(callbackCount==1,"Renderer publishes live telemetry for each DSP stage");expect(!result.telemetry.empty()&&result.telemetry[0].spectrumDbfs[0]>-120,"Dynamic EQ render emits spectrum telemetry");}
 {auto plan=planWith(module(MasteringModuleType::multibandCompressor,{{"lowCrossoverHz",120},{"midCrossoverHz",700},{"highCrossoverHz",4000},{"ratio",2},{"maximumGainReductionDb",4},{"low.thresholdDbfs",-30},{"lowMid.thresholdDbfs",-30},{"highMid.thresholdDbfs",-30},{"high.thresholdDbfs",-30},{"highMid.solo",1}}));const auto audition=temporary("solo-audition"),exported=temporary("solo-export"),exportOff=temporary("solo-export-off");(void)renderer.render(source,audition,plan,{},true);(void)renderer.render(source,exported,plan,{},false);plan.modules[0].parameters["highMid.solo"]=0;(void)renderer.render(source,exportOff,plan,{},false);expect(difference(read(audition),read(exported))>1,"Multiband Solo changes audition output");expect(difference(read(exported),read(exportOff))<1e-6,"Multiband Solo is excluded from export");}
 {auto plan=planWith(module(MasteringModuleType::stereoWidthMonoBass,{{"widthFactor",1},{"monoBassCrossoverHz",120},{"sideTrimDb",0},{"balance",0},{"monoCheck",1},{"swapLeftRight",0}}));const auto audition=temporary("mono-audition"),exported=temporary("mono-export"),exportOff=temporary("mono-export-off");const auto result=renderer.render(source,audition,plan,{},true);(void)renderer.render(source,exported,plan,{},false);plan.modules[0].parameters["monoCheck"]=0;(void)renderer.render(source,exportOff,plan,{},false);const auto auditionSamples=read(audition);double channelDifference=0;for(std::size_t i=0;i+1<auditionSamples.size();i+=2)channelDifference+=std::abs(auditionSamples[i]-auditionSamples[i+1]);expect(channelDifference<1e-5,"Mono Check produces mono audition output");expect(difference(read(audition),read(exported))>1,"Mono Check changes audition output");expect(difference(read(exported),read(exportOff))<1e-6,"Mono Check is excluded from export");expect(!result.telemetry.empty()&&!result.telemetry[0].vectorscope.empty()&&std::isfinite(result.telemetry[0].phaseCorrelation),"Stereo processor emits vectorscope and phase telemetry");}
 {auto plan=planWith(module(MasteringModuleType::truePeakLimiter,{{"inputGainDb",6},{"ceilingDbtp",-1},{"lookaheadMs",5},{"releaseMs",100},{"linked",1},{"truePeakEnabled",1}}));plan.targetIntegratedLufs=-4;int callbacks=0;const auto result=renderer.render(source,temporary("limiter-telemetry"),plan,{},true,[&callbacks](const ProcessorTelemetry&){++callbacks;});expect(callbacks==1&&result.telemetry.size()==1,"Limiter publishes live DSP telemetry");expect(result.telemetry[0].peakEventCount>0,"Limiter telemetry reports measured input peak events");expect(result.telemetry[0].maximumGainReductionDb>0,"Limiter telemetry reports measured gain reduction");}
 for(const auto&name:{"audition-source","dynamic-listen","dynamic-export","dynamic-export-off","solo-audition","solo-export","solo-export-off","mono-audition","mono-export","mono-export-off","limiter-telemetry"})std::filesystem::remove(temporary(name));if(failures==0)std::cout<<"All renderer audition/export tests passed\n";return failures==0?0:1;}
